package dbschema

import (
	"strings"
	"testing"
)

func TestBuildDocumentAndMarshalDocument(t *testing.T) {
	t.Parallel()

	doc := buildDocument(
		documentSource{
			Generator:    "go run ./cmd/schema",
			MigrationDir: "db/migrations",
			Migrations: []string{
				"000001_bootstrap.up.sql",
				"000002_mvp_core_entities.up.sql",
			},
		},
		catalog{
			Columns: []relationColumn{
				{
					SchemaName:      "app",
					RelationName:    "users",
					RelationKind:    "r",
					OrdinalPosition: 1,
					ColumnName:      "id",
					DataType:        "uuid",
					IsNullable:      false,
					ColumnDefault:   "gen_random_uuid()",
				},
				{
					SchemaName:      "app",
					RelationName:    "users",
					RelationKind:    "r",
					OrdinalPosition: 2,
					ColumnName:      "created_at",
					DataType:        "timestamp with time zone",
					IsNullable:      false,
					ColumnDefault:   "CURRENT_TIMESTAMP",
				},
				{
					SchemaName:      "app",
					RelationName:    "public_users",
					RelationKind:    "v",
					OrdinalPosition: 1,
					ColumnName:      "id",
					DataType:        "uuid",
					IsNullable:      true,
				},
			},
			Constraints: []tableConstraint{
				{
					SchemaName:     "app",
					TableName:      "users",
					ConstraintName: "users_pkey",
					ConstraintType: "p",
					Columns:        []string{"id"},
				},
				{
					SchemaName:     "app",
					TableName:      "users",
					ConstraintName: "users_created_at_key",
					ConstraintType: "u",
					Columns:        []string{"created_at"},
				},
				{
					SchemaName:     "app",
					TableName:      "users",
					ConstraintName: "users_created_at_check",
					ConstraintType: "c",
					Definition:     "CHECK (created_at IS NOT NULL)",
				},
			},
			Indexes: []tableIndex{
				{
					SchemaName: "app",
					TableName:  "users",
					IndexName:  "idx_users_created_at",
					Definition: "CREATE INDEX idx_users_created_at ON app.users USING btree (created_at)",
					Columns:    []string{"created_at"},
				},
			},
			Views: []viewDefinition{
				{
					SchemaName: "app",
					ViewName:   "public_users",
					Definition: " SELECT users.id\n   FROM app.users;",
				},
			},
		},
	)

	content, err := marshalDocument(doc)
	if err != nil {
		t.Fatalf("marshalDocument() error = %v, want nil", err)
	}

	rendered := string(content)

	for _, want := range []string{
		"# Code generated by go run ./cmd/schema. DO NOT EDIT.",
		"generator: go run ./cmd/schema",
		"migration_dir: db/migrations",
		"- 000001_bootstrap.up.sql",
		"name: users",
		"type: uuid",
		"default: gen_random_uuid()",
		"primary_key:",
		"unique_constraints:",
		"check_constraints:",
		"indexes:",
		"name: public_users",
		"definition: |",
	} {
		if !strings.Contains(rendered, want) {
			t.Fatalf("marshalDocument() output missing %q\n%s", want, rendered)
		}
	}
}

func TestForeignKeyAction(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		code string
		want string
	}{
		{name: "no action", code: "a", want: "NO ACTION"},
		{name: "restrict", code: "r", want: "RESTRICT"},
		{name: "cascade", code: "c", want: "CASCADE"},
		{name: "set null", code: "n", want: "SET NULL"},
		{name: "set default", code: "d", want: "SET DEFAULT"},
		{name: "unknown", code: "x", want: ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if got := foreignKeyAction(tt.code); got != tt.want {
				t.Fatalf("foreignKeyAction(%q) got %q want %q", tt.code, got, tt.want)
			}
		})
	}
}
