// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_login_challenges.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthLoginChallenge = `-- name: ConsumeAuthLoginChallenge :one
UPDATE app.auth_login_challenges
SET
    consumed_at = COALESCE($1::timestamptz, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, provider, provider_subject, email_normalized, challenge_token_hash, purpose, expires_at, consumed_at, attempt_count, created_at, updated_at
`

type ConsumeAuthLoginChallengeParams struct {
	ConsumedAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) ConsumeAuthLoginChallenge(ctx context.Context, arg ConsumeAuthLoginChallengeParams) (AppAuthLoginChallenge, error) {
	row := q.db.QueryRow(ctx, consumeAuthLoginChallenge, arg.ConsumedAt, arg.ID)
	var i AppAuthLoginChallenge
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.ChallengeTokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthLoginChallenge = `-- name: CreateAuthLoginChallenge :one
INSERT INTO app.auth_login_challenges (
    provider,
    provider_subject,
    email_normalized,
    challenge_token_hash,
    purpose,
    expires_at,
    consumed_at,
    attempt_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, provider, provider_subject, email_normalized, challenge_token_hash, purpose, expires_at, consumed_at, attempt_count, created_at, updated_at
`

type CreateAuthLoginChallengeParams struct {
	Provider           string
	ProviderSubject    string
	EmailNormalized    pgtype.Text
	ChallengeTokenHash string
	Purpose            string
	ExpiresAt          pgtype.Timestamptz
	ConsumedAt         pgtype.Timestamptz
	AttemptCount       int32
}

func (q *Queries) CreateAuthLoginChallenge(ctx context.Context, arg CreateAuthLoginChallengeParams) (AppAuthLoginChallenge, error) {
	row := q.db.QueryRow(ctx, createAuthLoginChallenge,
		arg.Provider,
		arg.ProviderSubject,
		arg.EmailNormalized,
		arg.ChallengeTokenHash,
		arg.Purpose,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.AttemptCount,
	)
	var i AppAuthLoginChallenge
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.ChallengeTokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPendingAuthLoginChallengeByProviderAndSubject = `-- name: GetLatestPendingAuthLoginChallengeByProviderAndSubject :one
SELECT id, provider, provider_subject, email_normalized, challenge_token_hash, purpose, expires_at, consumed_at, attempt_count, created_at, updated_at
FROM app.auth_login_challenges
WHERE provider = $1
    AND provider_subject = $2
    AND consumed_at IS NULL
    AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestPendingAuthLoginChallengeByProviderAndSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetLatestPendingAuthLoginChallengeByProviderAndSubject(ctx context.Context, arg GetLatestPendingAuthLoginChallengeByProviderAndSubjectParams) (AppAuthLoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLatestPendingAuthLoginChallengeByProviderAndSubject, arg.Provider, arg.ProviderSubject)
	var i AppAuthLoginChallenge
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.ChallengeTokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAuthLoginChallengeAttemptCount = `-- name: IncrementAuthLoginChallengeAttemptCount :one
UPDATE app.auth_login_challenges
SET
    attempt_count = attempt_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, provider, provider_subject, email_normalized, challenge_token_hash, purpose, expires_at, consumed_at, attempt_count, created_at, updated_at
`

func (q *Queries) IncrementAuthLoginChallengeAttemptCount(ctx context.Context, id pgtype.UUID) (AppAuthLoginChallenge, error) {
	row := q.db.QueryRow(ctx, incrementAuthLoginChallengeAttemptCount, id)
	var i AppAuthLoginChallenge
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.ChallengeTokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
