// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO app.auth_sessions (
    user_id,
    active_mode,
    session_token_hash,
    expires_at,
    last_seen_at,
    revoked_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5::timestamptz, CURRENT_TIMESTAMP),
    $6
)
RETURNING id, user_id, active_mode, session_token_hash, expires_at, last_seen_at, revoked_at, created_at, updated_at
`

type CreateAuthSessionParams struct {
	UserID           pgtype.UUID
	ActiveMode       string
	SessionTokenHash string
	ExpiresAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AppAuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.ActiveMode,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
	var i AppAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveMode,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAuthSessionByTokenHash = `-- name: GetActiveAuthSessionByTokenHash :one
SELECT id, user_id, active_mode, session_token_hash, expires_at, last_seen_at, revoked_at, created_at, updated_at
FROM app.auth_sessions
WHERE session_token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetActiveAuthSessionByTokenHash(ctx context.Context, sessionTokenHash string) (AppAuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSessionByTokenHash, sessionTokenHash)
	var i AppAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveMode,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentViewerBySessionTokenHash = `-- name: GetCurrentViewerBySessionTokenHash :one
SELECT
    s.user_id,
    s.active_mode,
    EXISTS (
        SELECT 1
        FROM app.creator_capabilities AS c
        WHERE c.user_id = s.user_id
            AND c.state = 'approved'
    ) AS can_access_creator_mode
FROM app.auth_sessions AS s
WHERE s.session_token_hash = $1
    AND s.revoked_at IS NULL
    AND s.expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type GetCurrentViewerBySessionTokenHashRow struct {
	UserID               pgtype.UUID
	ActiveMode           string
	CanAccessCreatorMode bool
}

func (q *Queries) GetCurrentViewerBySessionTokenHash(ctx context.Context, sessionTokenHash string) (GetCurrentViewerBySessionTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getCurrentViewerBySessionTokenHash, sessionTokenHash)
	var i GetCurrentViewerBySessionTokenHashRow
	err := row.Scan(&i.UserID, &i.ActiveMode, &i.CanAccessCreatorMode)
	return i, err
}

const listAuthSessionsByUserID = `-- name: ListAuthSessionsByUserID :many
SELECT id, user_id, active_mode, session_token_hash, expires_at, last_seen_at, revoked_at, created_at, updated_at
FROM app.auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAuthSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]AppAuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAuthSession
	for rows.Next() {
		var i AppAuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActiveMode,
			&i.SessionTokenHash,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :one
UPDATE app.auth_sessions
SET
    revoked_at = COALESCE($1::timestamptz, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, user_id, active_mode, session_token_hash, expires_at, last_seen_at, revoked_at, created_at, updated_at
`

type RevokeAuthSessionParams struct {
	RevokedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (AppAuthSession, error) {
	row := q.db.QueryRow(ctx, revokeAuthSession, arg.RevokedAt, arg.ID)
	var i AppAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveMode,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAuthSession = `-- name: TouchAuthSession :one
UPDATE app.auth_sessions
SET
    active_mode = $1,
    last_seen_at = COALESCE($2::timestamptz, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, user_id, active_mode, session_token_hash, expires_at, last_seen_at, revoked_at, created_at, updated_at
`

type TouchAuthSessionParams struct {
	ActiveMode string
	LastSeenAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) (AppAuthSession, error) {
	row := q.db.QueryRow(ctx, touchAuthSession, arg.ActiveMode, arg.LastSeenAt, arg.ID)
	var i AppAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActiveMode,
		&i.SessionTokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
