// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_identities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO app.auth_identities (
    user_id,
    provider,
    provider_subject,
    email_normalized,
    verified_at,
    last_authenticated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
`

type CreateAuthIdentityParams struct {
	UserID              pgtype.UUID
	Provider            string
	ProviderSubject     string
	EmailNormalized     pgtype.Text
	VerifiedAt          pgtype.Timestamptz
	LastAuthenticatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AppAuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.EmailNormalized,
		arg.VerifiedAt,
		arg.LastAuthenticatedAt,
	)
	var i AppAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.VerifiedAt,
		&i.LastAuthenticatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentityByEmailNormalized = `-- name: GetAuthIdentityByEmailNormalized :one
SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
FROM (
    SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
    FROM app.auth_identities AS auth_identities_email
    WHERE auth_identities_email.provider = 'email'
        AND auth_identities_email.email_normalized = $1

    UNION ALL

    SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
    FROM app.auth_identities AS auth_identities_cognito
    WHERE auth_identities_cognito.provider = 'cognito'
        AND auth_identities_cognito.email_normalized = $1

    UNION ALL

    SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
    FROM app.auth_identities AS auth_identities_other
    WHERE auth_identities_other.provider NOT IN ('email', 'cognito')
        AND auth_identities_other.email_normalized = $1
) AS auth_identities_by_email
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetAuthIdentityByEmailNormalized(ctx context.Context, targetEmailNormalized pgtype.Text) (AppAuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByEmailNormalized, targetEmailNormalized)
	var i AppAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.VerifiedAt,
		&i.LastAuthenticatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthIdentityByProviderAndSubject = `-- name: GetAuthIdentityByProviderAndSubject :one
SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
FROM app.auth_identities
WHERE provider = $1
    AND provider_subject = $2
LIMIT 1
`

type GetAuthIdentityByProviderAndSubjectParams struct {
	Provider        string
	ProviderSubject string
}

func (q *Queries) GetAuthIdentityByProviderAndSubject(ctx context.Context, arg GetAuthIdentityByProviderAndSubjectParams) (AppAuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByProviderAndSubject, arg.Provider, arg.ProviderSubject)
	var i AppAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.VerifiedAt,
		&i.LastAuthenticatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthIdentitiesByUserID = `-- name: ListAuthIdentitiesByUserID :many
SELECT id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
FROM app.auth_identities
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAuthIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]AppAuthIdentity, error) {
	rows, err := q.db.Query(ctx, listAuthIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAuthIdentity
	for rows.Next() {
		var i AppAuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.EmailNormalized,
			&i.VerifiedAt,
			&i.LastAuthenticatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthIdentityAuthentication = `-- name: RecordAuthIdentityAuthentication :one
UPDATE app.auth_identities
SET
    email_normalized = COALESCE($1, email_normalized),
    verified_at = COALESCE($2, verified_at),
    last_authenticated_at = COALESCE($3::timestamptz, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, user_id, provider, provider_subject, email_normalized, verified_at, last_authenticated_at, created_at, updated_at
`

type RecordAuthIdentityAuthenticationParams struct {
	EmailNormalized     pgtype.Text
	VerifiedAt          pgtype.Timestamptz
	LastAuthenticatedAt pgtype.Timestamptz
	ID                  pgtype.UUID
}

func (q *Queries) RecordAuthIdentityAuthentication(ctx context.Context, arg RecordAuthIdentityAuthenticationParams) (AppAuthIdentity, error) {
	row := q.db.QueryRow(ctx, recordAuthIdentityAuthentication,
		arg.EmailNormalized,
		arg.VerifiedAt,
		arg.LastAuthenticatedAt,
		arg.ID,
	)
	var i AppAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.EmailNormalized,
		&i.VerifiedAt,
		&i.LastAuthenticatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
