// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bootstrap.sql

package sqlc

import (
	"context"
)

const currentTimestamp = `-- name: CurrentTimestamp :one
SELECT CURRENT_TIMESTAMP AS current_timestamp
`

func (q *Queries) CurrentTimestamp(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, currentTimestamp)
	var current_timestamp interface{}
	err := row.Scan(&current_timestamp)
	return current_timestamp, err
}
