// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_registration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCreatorRegistrationIntakeByUserID = `-- name: GetCreatorRegistrationIntakeByUserID :one
SELECT user_id, legal_name, birth_date, payout_recipient_type, payout_recipient_name, declares_no_prohibited_category, accepts_consent_responsibility, created_at, updated_at
FROM app.creator_registration_intakes
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetCreatorRegistrationIntakeByUserID(ctx context.Context, userID pgtype.UUID) (AppCreatorRegistrationIntake, error) {
	row := q.db.QueryRow(ctx, getCreatorRegistrationIntakeByUserID, userID)
	var i AppCreatorRegistrationIntake
	err := row.Scan(
		&i.UserID,
		&i.LegalName,
		&i.BirthDate,
		&i.PayoutRecipientType,
		&i.PayoutRecipientName,
		&i.DeclaresNoProhibitedCategory,
		&i.AcceptsConsentResponsibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreatorRegistrationEvidencesByUserID = `-- name: ListCreatorRegistrationEvidencesByUserID :many
SELECT user_id, kind, file_name, mime_type, file_size_bytes, storage_bucket, storage_key, uploaded_at, created_at, updated_at
FROM app.creator_registration_evidences
WHERE user_id = $1
ORDER BY kind ASC
`

func (q *Queries) ListCreatorRegistrationEvidencesByUserID(ctx context.Context, userID pgtype.UUID) ([]AppCreatorRegistrationEvidence, error) {
	rows, err := q.db.Query(ctx, listCreatorRegistrationEvidencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCreatorRegistrationEvidence
	for rows.Next() {
		var i AppCreatorRegistrationEvidence
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.FileName,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.StorageBucket,
			&i.StorageKey,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatorRegistrationReviewCasesByState = `-- name: ListCreatorRegistrationReviewCasesByState :many
SELECT
    c.user_id,
    c.state,
    c.submitted_at,
    c.approved_at,
    c.rejected_at,
    c.suspended_at,
    u.display_name,
    u.handle,
    u.avatar_url,
    COALESCE(p.bio, '') AS creator_bio,
    COALESCE(i.legal_name, '') AS legal_name
FROM app.creator_capabilities AS c
JOIN app.user_profiles AS u
    ON u.user_id = c.user_id
LEFT JOIN app.creator_profiles AS p
    ON p.user_id = c.user_id
LEFT JOIN app.creator_registration_intakes AS i
    ON i.user_id = c.user_id
WHERE c.state = $1
ORDER BY
    COALESCE(c.submitted_at, c.approved_at, c.rejected_at, c.suspended_at) DESC,
    c.user_id ASC
`

type ListCreatorRegistrationReviewCasesByStateRow struct {
	UserID      pgtype.UUID
	State       string
	SubmittedAt pgtype.Timestamptz
	ApprovedAt  pgtype.Timestamptz
	RejectedAt  pgtype.Timestamptz
	SuspendedAt pgtype.Timestamptz
	DisplayName string
	Handle      string
	AvatarUrl   pgtype.Text
	CreatorBio  string
	LegalName   string
}

func (q *Queries) ListCreatorRegistrationReviewCasesByState(ctx context.Context, state string) ([]ListCreatorRegistrationReviewCasesByStateRow, error) {
	rows, err := q.db.Query(ctx, listCreatorRegistrationReviewCasesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatorRegistrationReviewCasesByStateRow
	for rows.Next() {
		var i ListCreatorRegistrationReviewCasesByStateRow
		if err := rows.Scan(
			&i.UserID,
			&i.State,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.SuspendedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.CreatorBio,
			&i.LegalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreatorRegistrationEvidence = `-- name: UpsertCreatorRegistrationEvidence :one
INSERT INTO app.creator_registration_evidences (
    user_id,
    kind,
    file_name,
    mime_type,
    file_size_bytes,
    storage_bucket,
    storage_key,
    uploaded_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (user_id, kind) DO UPDATE
SET
    file_name = EXCLUDED.file_name,
    mime_type = EXCLUDED.mime_type,
    file_size_bytes = EXCLUDED.file_size_bytes,
    storage_bucket = EXCLUDED.storage_bucket,
    storage_key = EXCLUDED.storage_key,
    uploaded_at = EXCLUDED.uploaded_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, kind, file_name, mime_type, file_size_bytes, storage_bucket, storage_key, uploaded_at, created_at, updated_at
`

type UpsertCreatorRegistrationEvidenceParams struct {
	UserID        pgtype.UUID
	Kind          string
	FileName      string
	MimeType      string
	FileSizeBytes int64
	StorageBucket string
	StorageKey    string
	UploadedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCreatorRegistrationEvidence(ctx context.Context, arg UpsertCreatorRegistrationEvidenceParams) (AppCreatorRegistrationEvidence, error) {
	row := q.db.QueryRow(ctx, upsertCreatorRegistrationEvidence,
		arg.UserID,
		arg.Kind,
		arg.FileName,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.StorageBucket,
		arg.StorageKey,
		arg.UploadedAt,
	)
	var i AppCreatorRegistrationEvidence
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.FileName,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.StorageBucket,
		&i.StorageKey,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCreatorRegistrationIntake = `-- name: UpsertCreatorRegistrationIntake :one
INSERT INTO app.creator_registration_intakes (
    user_id,
    legal_name,
    birth_date,
    payout_recipient_type,
    payout_recipient_name,
    declares_no_prohibited_category,
    accepts_consent_responsibility
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (user_id) DO UPDATE
SET
    legal_name = EXCLUDED.legal_name,
    birth_date = EXCLUDED.birth_date,
    payout_recipient_type = EXCLUDED.payout_recipient_type,
    payout_recipient_name = EXCLUDED.payout_recipient_name,
    declares_no_prohibited_category = EXCLUDED.declares_no_prohibited_category,
    accepts_consent_responsibility = EXCLUDED.accepts_consent_responsibility,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, legal_name, birth_date, payout_recipient_type, payout_recipient_name, declares_no_prohibited_category, accepts_consent_responsibility, created_at, updated_at
`

type UpsertCreatorRegistrationIntakeParams struct {
	UserID                       pgtype.UUID
	LegalName                    string
	BirthDate                    pgtype.Date
	PayoutRecipientType          pgtype.Text
	PayoutRecipientName          string
	DeclaresNoProhibitedCategory bool
	AcceptsConsentResponsibility bool
}

func (q *Queries) UpsertCreatorRegistrationIntake(ctx context.Context, arg UpsertCreatorRegistrationIntakeParams) (AppCreatorRegistrationIntake, error) {
	row := q.db.QueryRow(ctx, upsertCreatorRegistrationIntake,
		arg.UserID,
		arg.LegalName,
		arg.BirthDate,
		arg.PayoutRecipientType,
		arg.PayoutRecipientName,
		arg.DeclaresNoProhibitedCategory,
		arg.AcceptsConsentResponsibility,
	)
	var i AppCreatorRegistrationIntake
	err := row.Scan(
		&i.UserID,
		&i.LegalName,
		&i.BirthDate,
		&i.PayoutRecipientType,
		&i.PayoutRecipientName,
		&i.DeclaresNoProhibitedCategory,
		&i.AcceptsConsentResponsibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
