// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreatorFollowersByCreatorUserID = `-- name: CountCreatorFollowersByCreatorUserID :one
SELECT COUNT(*)::bigint
FROM app.creator_follows
WHERE creator_user_id = $1
`

func (q *Queries) CountCreatorFollowersByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCreatorFollowersByCreatorUserID, creatorUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCreatorProfile = `-- name: CreateCreatorProfile :one
INSERT INTO app.creator_profiles (
    user_id,
    display_name,
    handle,
    avatar_url,
    bio,
    published_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
`

type CreateCreatorProfileParams struct {
	UserID      pgtype.UUID
	DisplayName pgtype.Text
	Handle      pgtype.Text
	AvatarUrl   pgtype.Text
	Bio         string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) CreateCreatorProfile(ctx context.Context, arg CreateCreatorProfileParams) (AppCreatorProfile, error) {
	row := q.db.QueryRow(ctx, createCreatorProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.Bio,
		arg.PublishedAt,
	)
	var i AppCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}

const getCreatorProfileByUserID = `-- name: GetCreatorProfileByUserID :one
SELECT user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
FROM app.creator_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetCreatorProfileByUserID(ctx context.Context, userID pgtype.UUID) (AppCreatorProfile, error) {
	row := q.db.QueryRow(ctx, getCreatorProfileByUserID, userID)
	var i AppCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}

const getPublicCreatorProfileByHandle = `-- name: GetPublicCreatorProfileByHandle :one
SELECT user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
FROM app.public_creator_profiles
WHERE handle = $1
LIMIT 1
`

func (q *Queries) GetPublicCreatorProfileByHandle(ctx context.Context, handle pgtype.Text) (AppPublicCreatorProfile, error) {
	row := q.db.QueryRow(ctx, getPublicCreatorProfileByHandle, handle)
	var i AppPublicCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}

const getPublicCreatorProfileByUserID = `-- name: GetPublicCreatorProfileByUserID :one
SELECT user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
FROM app.public_creator_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetPublicCreatorProfileByUserID(ctx context.Context, userID pgtype.UUID) (AppPublicCreatorProfile, error) {
	row := q.db.QueryRow(ctx, getPublicCreatorProfileByUserID, userID)
	var i AppPublicCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}

const listRecentPublicCreatorProfiles = `-- name: ListRecentPublicCreatorProfiles :many
SELECT user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
FROM app.public_creator_profiles
WHERE (
    $1::timestamptz IS NULL
    OR published_at < $1::timestamptz
    OR (
        published_at = $1::timestamptz
        AND handle > COALESCE($2::text, '')
    )
)
ORDER BY published_at DESC, handle ASC
LIMIT $3
`

type ListRecentPublicCreatorProfilesParams struct {
	CursorPublishedAt pgtype.Timestamptz
	CursorHandle      pgtype.Text
	LimitCount        int32
}

func (q *Queries) ListRecentPublicCreatorProfiles(ctx context.Context, arg ListRecentPublicCreatorProfilesParams) ([]AppPublicCreatorProfile, error) {
	rows, err := q.db.Query(ctx, listRecentPublicCreatorProfiles, arg.CursorPublishedAt, arg.CursorHandle, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPublicCreatorProfile
	for rows.Next() {
		var i AppPublicCreatorProfile
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishCreatorProfile = `-- name: PublishCreatorProfile :one
UPDATE app.creator_profiles
SET
    published_at = COALESCE(published_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
RETURNING user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
`

func (q *Queries) PublishCreatorProfile(ctx context.Context, userID pgtype.UUID) (AppCreatorProfile, error) {
	row := q.db.QueryRow(ctx, publishCreatorProfile, userID)
	var i AppCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}

const searchPublicCreatorProfiles = `-- name: SearchPublicCreatorProfiles :many
SELECT user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
FROM app.public_creator_profiles
WHERE (
    display_name ILIKE '%' || $1 || '%' ESCAPE '\'
    OR (
        $2 <> ''
        AND handle LIKE $2 || '%' ESCAPE '\'
    )
)
AND (
    $3::timestamptz IS NULL
    OR published_at < $3::timestamptz
    OR (
        published_at = $3::timestamptz
        AND handle > COALESCE($4::text, '')
    )
)
ORDER BY published_at DESC, handle ASC
LIMIT $5
`

type SearchPublicCreatorProfilesParams struct {
	DisplayNameQuery  pgtype.Text
	HandlePrefixQuery interface{}
	CursorPublishedAt pgtype.Timestamptz
	CursorHandle      pgtype.Text
	LimitCount        int32
}

func (q *Queries) SearchPublicCreatorProfiles(ctx context.Context, arg SearchPublicCreatorProfilesParams) ([]AppPublicCreatorProfile, error) {
	rows, err := q.db.Query(ctx, searchPublicCreatorProfiles,
		arg.DisplayNameQuery,
		arg.HandlePrefixQuery,
		arg.CursorPublishedAt,
		arg.CursorHandle,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPublicCreatorProfile
	for rows.Next() {
		var i AppPublicCreatorProfile
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Bio,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreatorProfile = `-- name: UpdateCreatorProfile :one
UPDATE app.creator_profiles
SET
    display_name = $1,
    handle = $2,
    avatar_url = $3,
    bio = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $5
RETURNING user_id, display_name, avatar_url, bio, published_at, created_at, updated_at, handle
`

type UpdateCreatorProfileParams struct {
	DisplayName pgtype.Text
	Handle      pgtype.Text
	AvatarUrl   pgtype.Text
	Bio         string
	UserID      pgtype.UUID
}

func (q *Queries) UpdateCreatorProfile(ctx context.Context, arg UpdateCreatorProfileParams) (AppCreatorProfile, error) {
	row := q.db.QueryRow(ctx, updateCreatorProfile,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.Bio,
		arg.UserID,
	)
	var i AppCreatorProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
	)
	return i, err
}
