// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCreatorWorkspaceOverviewMetrics = `-- name: GetCreatorWorkspaceOverviewMetrics :one
SELECT
    COALESCE(
        SUM(
            CASE
                WHEN mu.user_id IS NULL THEN 0
                ELSE COALESCE(m.price_minor, 0)
            END
        ),
        0
    )::bigint AS gross_unlock_revenue_jpy,
    COUNT(mu.main_id)::bigint AS unlock_count,
    COUNT(DISTINCT mu.user_id)::bigint AS unique_purchaser_count
FROM app.mains AS m
LEFT JOIN app.main_unlocks AS mu
    ON mu.main_id = m.id
WHERE m.creator_user_id = $1
`

type GetCreatorWorkspaceOverviewMetricsRow struct {
	GrossUnlockRevenueJpy int64
	UnlockCount           int64
	UniquePurchaserCount  int64
}

func (q *Queries) GetCreatorWorkspaceOverviewMetrics(ctx context.Context, ownerUserID pgtype.UUID) (GetCreatorWorkspaceOverviewMetricsRow, error) {
	row := q.db.QueryRow(ctx, getCreatorWorkspaceOverviewMetrics, ownerUserID)
	var i GetCreatorWorkspaceOverviewMetricsRow
	err := row.Scan(&i.GrossUnlockRevenueJpy, &i.UnlockCount, &i.UniquePurchaserCount)
	return i, err
}

const getCreatorWorkspaceRevisionRequestedSummary = `-- name: GetCreatorWorkspaceRevisionRequestedSummary :one
SELECT
    (
        SELECT COUNT(*)::bigint
        FROM app.mains AS m
        WHERE m.creator_user_id = $1
            AND m.state = 'revision_requested'
    ) AS main_count,
    (
        SELECT COUNT(*)::bigint
        FROM app.shorts AS s
        WHERE s.creator_user_id = $1
            AND s.state = 'revision_requested'
    ) AS short_count
`

type GetCreatorWorkspaceRevisionRequestedSummaryRow struct {
	MainCount  int64
	ShortCount int64
}

func (q *Queries) GetCreatorWorkspaceRevisionRequestedSummary(ctx context.Context, ownerUserID pgtype.UUID) (GetCreatorWorkspaceRevisionRequestedSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCreatorWorkspaceRevisionRequestedSummary, ownerUserID)
	var i GetCreatorWorkspaceRevisionRequestedSummaryRow
	err := row.Scan(&i.MainCount, &i.ShortCount)
	return i, err
}

const listCreatorWorkspacePreviewMainsByCreatorUserID = `-- name: ListCreatorWorkspacePreviewMainsByCreatorUserID :many
SELECT
    id,
    creator_user_id,
    media_asset_id,
    state,
    review_reason_code,
    post_report_state,
    COALESCE(price_minor, 0)::bigint AS price_minor,
    COALESCE(currency_code, '')::text AS currency_code,
    ownership_confirmed,
    consent_confirmed,
    approved_for_unlock_at,
    created_at,
    updated_at
FROM app.mains
WHERE creator_user_id = $1
    AND media_asset_id IS NOT NULL
    AND price_minor IS NOT NULL
    AND currency_code IS NOT NULL
ORDER BY created_at DESC, id DESC
`

type ListCreatorWorkspacePreviewMainsByCreatorUserIDRow struct {
	ID                  pgtype.UUID
	CreatorUserID       pgtype.UUID
	MediaAssetID        pgtype.UUID
	State               string
	ReviewReasonCode    pgtype.Text
	PostReportState     pgtype.Text
	PriceMinor          int64
	CurrencyCode        string
	OwnershipConfirmed  bool
	ConsentConfirmed    bool
	ApprovedForUnlockAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ListCreatorWorkspacePreviewMainsByCreatorUserID(ctx context.Context, ownerUserID pgtype.UUID) ([]ListCreatorWorkspacePreviewMainsByCreatorUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCreatorWorkspacePreviewMainsByCreatorUserID, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatorWorkspacePreviewMainsByCreatorUserIDRow
	for rows.Next() {
		var i ListCreatorWorkspacePreviewMainsByCreatorUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.PriceMinor,
			&i.CurrencyCode,
			&i.OwnershipConfirmed,
			&i.ConsentConfirmed,
			&i.ApprovedForUnlockAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
