// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCreatorWorkspaceOverviewMetrics = `-- name: GetCreatorWorkspaceOverviewMetrics :one
SELECT
    COALESCE(
        SUM(
            CASE
                WHEN mu.user_id IS NULL THEN 0
                ELSE COALESCE(m.price_minor, 0)
            END
        ),
        0
    )::bigint AS gross_unlock_revenue_jpy,
    COUNT(mu.main_id)::bigint AS unlock_count,
    COUNT(DISTINCT mu.user_id)::bigint AS unique_purchaser_count
FROM app.mains AS m
LEFT JOIN app.main_unlocks AS mu
    ON mu.main_id = m.id
WHERE m.creator_user_id = $1
`

type GetCreatorWorkspaceOverviewMetricsRow struct {
	GrossUnlockRevenueJpy int64
	UnlockCount           int64
	UniquePurchaserCount  int64
}

func (q *Queries) GetCreatorWorkspaceOverviewMetrics(ctx context.Context, ownerUserID pgtype.UUID) (GetCreatorWorkspaceOverviewMetricsRow, error) {
	row := q.db.QueryRow(ctx, getCreatorWorkspaceOverviewMetrics, ownerUserID)
	var i GetCreatorWorkspaceOverviewMetricsRow
	err := row.Scan(&i.GrossUnlockRevenueJpy, &i.UnlockCount, &i.UniquePurchaserCount)
	return i, err
}

const getCreatorWorkspaceRevisionRequestedSummary = `-- name: GetCreatorWorkspaceRevisionRequestedSummary :one
SELECT
    (
        SELECT COUNT(*)::bigint
        FROM app.mains AS m
        WHERE m.creator_user_id = $1
            AND m.state = 'revision_requested'
    ) AS main_count,
    (
        SELECT COUNT(*)::bigint
        FROM app.shorts AS s
        WHERE s.creator_user_id = $1
            AND s.state = 'revision_requested'
    ) AS short_count
`

type GetCreatorWorkspaceRevisionRequestedSummaryRow struct {
	MainCount  int64
	ShortCount int64
}

func (q *Queries) GetCreatorWorkspaceRevisionRequestedSummary(ctx context.Context, ownerUserID pgtype.UUID) (GetCreatorWorkspaceRevisionRequestedSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCreatorWorkspaceRevisionRequestedSummary, ownerUserID)
	var i GetCreatorWorkspaceRevisionRequestedSummaryRow
	err := row.Scan(&i.MainCount, &i.ShortCount)
	return i, err
}
