// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_capabilities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreatorCapability = `-- name: CreateCreatorCapability :one
INSERT INTO app.creator_capabilities (
    user_id,
    state,
    rejection_reason_code,
    is_resubmit_eligible,
    is_support_review_required,
    self_serve_resubmit_count,
    kyc_provider_case_ref,
    payout_provider_account_ref,
    submitted_at,
    approved_at,
    rejected_at,
    suspended_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING user_id, state, rejection_reason_code, is_resubmit_eligible, is_support_review_required, self_serve_resubmit_count, kyc_provider_case_ref, payout_provider_account_ref, submitted_at, approved_at, rejected_at, suspended_at, created_at, updated_at
`

type CreateCreatorCapabilityParams struct {
	UserID                   pgtype.UUID
	State                    string
	RejectionReasonCode      pgtype.Text
	IsResubmitEligible       bool
	IsSupportReviewRequired  bool
	SelfServeResubmitCount   int32
	KycProviderCaseRef       pgtype.Text
	PayoutProviderAccountRef pgtype.Text
	SubmittedAt              pgtype.Timestamptz
	ApprovedAt               pgtype.Timestamptz
	RejectedAt               pgtype.Timestamptz
	SuspendedAt              pgtype.Timestamptz
}

func (q *Queries) CreateCreatorCapability(ctx context.Context, arg CreateCreatorCapabilityParams) (AppCreatorCapability, error) {
	row := q.db.QueryRow(ctx, createCreatorCapability,
		arg.UserID,
		arg.State,
		arg.RejectionReasonCode,
		arg.IsResubmitEligible,
		arg.IsSupportReviewRequired,
		arg.SelfServeResubmitCount,
		arg.KycProviderCaseRef,
		arg.PayoutProviderAccountRef,
		arg.SubmittedAt,
		arg.ApprovedAt,
		arg.RejectedAt,
		arg.SuspendedAt,
	)
	var i AppCreatorCapability
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.RejectionReasonCode,
		&i.IsResubmitEligible,
		&i.IsSupportReviewRequired,
		&i.SelfServeResubmitCount,
		&i.KycProviderCaseRef,
		&i.PayoutProviderAccountRef,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreatorCapabilityByUserID = `-- name: GetCreatorCapabilityByUserID :one
SELECT user_id, state, rejection_reason_code, is_resubmit_eligible, is_support_review_required, self_serve_resubmit_count, kyc_provider_case_ref, payout_provider_account_ref, submitted_at, approved_at, rejected_at, suspended_at, created_at, updated_at
FROM app.creator_capabilities
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetCreatorCapabilityByUserID(ctx context.Context, userID pgtype.UUID) (AppCreatorCapability, error) {
	row := q.db.QueryRow(ctx, getCreatorCapabilityByUserID, userID)
	var i AppCreatorCapability
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.RejectionReasonCode,
		&i.IsResubmitEligible,
		&i.IsSupportReviewRequired,
		&i.SelfServeResubmitCount,
		&i.KycProviderCaseRef,
		&i.PayoutProviderAccountRef,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreatorCapabilityByUserIDForUpdate = `-- name: GetCreatorCapabilityByUserIDForUpdate :one
SELECT user_id, state, rejection_reason_code, is_resubmit_eligible, is_support_review_required, self_serve_resubmit_count, kyc_provider_case_ref, payout_provider_account_ref, submitted_at, approved_at, rejected_at, suspended_at, created_at, updated_at
FROM app.creator_capabilities
WHERE user_id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetCreatorCapabilityByUserIDForUpdate(ctx context.Context, userID pgtype.UUID) (AppCreatorCapability, error) {
	row := q.db.QueryRow(ctx, getCreatorCapabilityByUserIDForUpdate, userID)
	var i AppCreatorCapability
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.RejectionReasonCode,
		&i.IsResubmitEligible,
		&i.IsSupportReviewRequired,
		&i.SelfServeResubmitCount,
		&i.KycProviderCaseRef,
		&i.PayoutProviderAccountRef,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreatorCapabilityState = `-- name: UpdateCreatorCapabilityState :one
UPDATE app.creator_capabilities
SET
    state = $1,
    rejection_reason_code = $2,
    is_resubmit_eligible = $3,
    is_support_review_required = $4,
    self_serve_resubmit_count = $5,
    kyc_provider_case_ref = $6,
    payout_provider_account_ref = $7,
    submitted_at = $8,
    approved_at = $9,
    rejected_at = $10,
    suspended_at = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $12
RETURNING user_id, state, rejection_reason_code, is_resubmit_eligible, is_support_review_required, self_serve_resubmit_count, kyc_provider_case_ref, payout_provider_account_ref, submitted_at, approved_at, rejected_at, suspended_at, created_at, updated_at
`

type UpdateCreatorCapabilityStateParams struct {
	State                    string
	RejectionReasonCode      pgtype.Text
	IsResubmitEligible       bool
	IsSupportReviewRequired  bool
	SelfServeResubmitCount   int32
	KycProviderCaseRef       pgtype.Text
	PayoutProviderAccountRef pgtype.Text
	SubmittedAt              pgtype.Timestamptz
	ApprovedAt               pgtype.Timestamptz
	RejectedAt               pgtype.Timestamptz
	SuspendedAt              pgtype.Timestamptz
	UserID                   pgtype.UUID
}

func (q *Queries) UpdateCreatorCapabilityState(ctx context.Context, arg UpdateCreatorCapabilityStateParams) (AppCreatorCapability, error) {
	row := q.db.QueryRow(ctx, updateCreatorCapabilityState,
		arg.State,
		arg.RejectionReasonCode,
		arg.IsResubmitEligible,
		arg.IsSupportReviewRequired,
		arg.SelfServeResubmitCount,
		arg.KycProviderCaseRef,
		arg.PayoutProviderAccountRef,
		arg.SubmittedAt,
		arg.ApprovedAt,
		arg.RejectedAt,
		arg.SuspendedAt,
		arg.UserID,
	)
	var i AppCreatorCapability
	err := row.Scan(
		&i.UserID,
		&i.State,
		&i.RejectionReasonCode,
		&i.IsResubmitEligible,
		&i.IsSupportReviewRequired,
		&i.SelfServeResubmitCount,
		&i.KycProviderCaseRef,
		&i.PayoutProviderAccountRef,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
