// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRecommendedFeedItems = `-- name: ListRecommendedFeedItems :many
SELECT
    s.id AS short_id,
    s.canonical_main_id,
    s.creator_user_id,
    s.title AS short_title,
    s.caption AS short_caption,
    s.media_asset_id AS short_media_asset_id,
    s.published_at AS short_published_at,
    short_media.playback_url AS short_playback_url,
    short_media.duration_ms AS short_duration_ms,
    c.display_name AS creator_display_name,
    c.handle AS creator_handle,
    c.avatar_url AS creator_avatar_url,
    c.bio AS creator_bio,
    m.id AS main_id,
    m.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
    AND short_media.creator_user_id = s.creator_user_id
    AND short_media.processing_state = 'ready'
JOIN app.public_creator_profiles AS c
    ON c.user_id = s.creator_user_id
JOIN app.unlockable_mains AS m
    ON m.id = s.canonical_main_id
    AND m.creator_user_id = s.creator_user_id
JOIN app.media_assets AS main_media
    ON main_media.id = m.media_asset_id
    AND main_media.creator_user_id = m.creator_user_id
    AND main_media.processing_state = 'ready'
WHERE (
    $1::timestamptz IS NULL
    OR s.published_at < $1::timestamptz
    OR (
        s.published_at = $1::timestamptz
        AND s.id < $2::uuid
    )
)
    AND m.price_minor IS NOT NULL
    AND m.currency_code = 'JPY'
ORDER BY s.published_at DESC, s.id DESC
LIMIT $3
`

type ListRecommendedFeedItemsParams struct {
	CursorPublishedAt pgtype.Timestamptz
	CursorShortID     pgtype.UUID
	PageLimit         int32
}

type ListRecommendedFeedItemsRow struct {
	ShortID            pgtype.UUID
	CanonicalMainID    pgtype.UUID
	CreatorUserID      pgtype.UUID
	ShortTitle         string
	ShortCaption       string
	ShortMediaAssetID  pgtype.UUID
	ShortPublishedAt   pgtype.Timestamptz
	ShortPlaybackUrl   pgtype.Text
	ShortDurationMs    pgtype.Int8
	CreatorDisplayName pgtype.Text
	CreatorHandle      pgtype.Text
	CreatorAvatarUrl   pgtype.Text
	CreatorBio         string
	MainID             pgtype.UUID
	MainPriceMinor     pgtype.Int8
	MainDurationMs     pgtype.Int8
}

func (q *Queries) ListRecommendedFeedItems(ctx context.Context, arg ListRecommendedFeedItemsParams) ([]ListRecommendedFeedItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendedFeedItems, arg.CursorPublishedAt, arg.CursorShortID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendedFeedItemsRow
	for rows.Next() {
		var i ListRecommendedFeedItemsRow
		if err := rows.Scan(
			&i.ShortID,
			&i.CanonicalMainID,
			&i.CreatorUserID,
			&i.ShortTitle,
			&i.ShortCaption,
			&i.ShortMediaAssetID,
			&i.ShortPublishedAt,
			&i.ShortPlaybackUrl,
			&i.ShortDurationMs,
			&i.CreatorDisplayName,
			&i.CreatorHandle,
			&i.CreatorAvatarUrl,
			&i.CreatorBio,
			&i.MainID,
			&i.MainPriceMinor,
			&i.MainDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
