// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: following.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFanProfileFollowingItems = `-- name: ListFanProfileFollowingItems :many
SELECT
    p.user_id AS creator_user_id,
    p.display_name,
    p.handle,
    p.avatar_url,
    p.bio,
    cf.followed_at
FROM app.creator_follows AS cf
JOIN app.public_creator_profiles AS p
    ON p.user_id = cf.creator_user_id
WHERE cf.user_id = $1
AND (
    $2::timestamptz IS NULL
    OR cf.followed_at < $2::timestamptz
    OR (
        cf.followed_at = $2::timestamptz
        AND cf.creator_user_id > COALESCE(
            $3::uuid,
            '00000000-0000-0000-0000-000000000000'::uuid
        )
    )
)
ORDER BY cf.followed_at DESC, cf.creator_user_id ASC
LIMIT $4
`

type ListFanProfileFollowingItemsParams struct {
	UserID              pgtype.UUID
	CursorFollowedAt    pgtype.Timestamptz
	CursorCreatorUserID pgtype.UUID
	LimitCount          int32
}

type ListFanProfileFollowingItemsRow struct {
	CreatorUserID pgtype.UUID
	DisplayName   pgtype.Text
	Handle        pgtype.Text
	AvatarUrl     pgtype.Text
	Bio           string
	FollowedAt    pgtype.Timestamptz
}

func (q *Queries) ListFanProfileFollowingItems(ctx context.Context, arg ListFanProfileFollowingItemsParams) ([]ListFanProfileFollowingItemsRow, error) {
	rows, err := q.db.Query(ctx, listFanProfileFollowingItems,
		arg.UserID,
		arg.CursorFollowedAt,
		arg.CursorCreatorUserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFanProfileFollowingItemsRow
	for rows.Next() {
		var i ListFanProfileFollowingItemsRow
		if err := rows.Scan(
			&i.CreatorUserID,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.FollowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
