// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: library.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFanProfileLibraryItems = `-- name: ListFanProfileLibraryItems :many
SELECT
    unlock.main_id,
    unlock.purchased_at,
    unlock.created_at AS unlock_created_at,
    main.creator_user_id,
    main_media.duration_ms AS main_duration_ms,
    profile.display_name,
    profile.handle,
    profile.avatar_url,
    profile.bio,
    entry_short.id AS entry_short_id,
    entry_short.canonical_main_id AS entry_short_canonical_main_id,
    entry_short.caption AS entry_short_caption,
    entry_short.media_asset_id AS entry_short_media_asset_id,
    entry_short_media.duration_ms AS entry_short_duration_ms
FROM app.main_unlocks AS unlock
JOIN app.unlockable_mains AS main
    ON main.id = unlock.main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main.media_asset_id
JOIN app.public_creator_profiles AS profile
    ON profile.user_id = main.creator_user_id
JOIN LATERAL (
    SELECT
        short.id,
        short.canonical_main_id,
        short.caption,
        short.media_asset_id
    FROM app.public_shorts AS short
    WHERE short.canonical_main_id = main.id
    ORDER BY short.published_at DESC, short.created_at DESC, short.id DESC
    LIMIT 1
) AS entry_short
    ON TRUE
JOIN app.media_assets AS entry_short_media
    ON entry_short_media.id = entry_short.media_asset_id
WHERE unlock.user_id = $1
AND (
    $2::timestamptz IS NULL
    OR unlock.purchased_at < $2::timestamptz
    OR (
        unlock.purchased_at = $2::timestamptz
        AND (
            unlock.created_at < COALESCE(
                $3::timestamptz,
                'infinity'::timestamptz
            )
            OR (
                unlock.created_at = COALESCE(
                    $3::timestamptz,
                    'infinity'::timestamptz
                )
                AND unlock.main_id < COALESCE(
                    $4::uuid,
                    'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid
                )
            )
        )
    )
)
ORDER BY unlock.purchased_at DESC, unlock.created_at DESC, unlock.main_id DESC
LIMIT $5
`

type ListFanProfileLibraryItemsParams struct {
	UserID                pgtype.UUID
	CursorPurchasedAt     pgtype.Timestamptz
	CursorUnlockCreatedAt pgtype.Timestamptz
	CursorMainID          pgtype.UUID
	LimitCount            int32
}

type ListFanProfileLibraryItemsRow struct {
	MainID                    pgtype.UUID
	PurchasedAt               pgtype.Timestamptz
	UnlockCreatedAt           pgtype.Timestamptz
	CreatorUserID             pgtype.UUID
	MainDurationMs            pgtype.Int8
	DisplayName               pgtype.Text
	Handle                    string
	AvatarUrl                 pgtype.Text
	Bio                       string
	EntryShortID              pgtype.UUID
	EntryShortCanonicalMainID pgtype.UUID
	EntryShortCaption         pgtype.Text
	EntryShortMediaAssetID    pgtype.UUID
	EntryShortDurationMs      pgtype.Int8
}

func (q *Queries) ListFanProfileLibraryItems(ctx context.Context, arg ListFanProfileLibraryItemsParams) ([]ListFanProfileLibraryItemsRow, error) {
	rows, err := q.db.Query(ctx, listFanProfileLibraryItems,
		arg.UserID,
		arg.CursorPurchasedAt,
		arg.CursorUnlockCreatedAt,
		arg.CursorMainID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFanProfileLibraryItemsRow
	for rows.Next() {
		var i ListFanProfileLibraryItemsRow
		if err := rows.Scan(
			&i.MainID,
			&i.PurchasedAt,
			&i.UnlockCreatedAt,
			&i.CreatorUserID,
			&i.MainDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.EntryShortID,
			&i.EntryShortCanonicalMainID,
			&i.EntryShortCaption,
			&i.EntryShortMediaAssetID,
			&i.EntryShortDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
