// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMain = `-- name: CreateMain :one
INSERT INTO app.mains (
    creator_user_id,
    media_asset_id,
    state,
    review_reason_code,
    post_report_state,
    price_minor,
    currency_code,
    ownership_confirmed,
    consent_confirmed,
    approved_for_unlock_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, creator_user_id, media_asset_id, state, review_reason_code, post_report_state, price_minor, currency_code, ownership_confirmed, consent_confirmed, approved_for_unlock_at, created_at, updated_at
`

type CreateMainParams struct {
	CreatorUserID       pgtype.UUID
	MediaAssetID        pgtype.UUID
	State               string
	ReviewReasonCode    pgtype.Text
	PostReportState     pgtype.Text
	PriceMinor          int64
	CurrencyCode        string
	OwnershipConfirmed  bool
	ConsentConfirmed    bool
	ApprovedForUnlockAt pgtype.Timestamptz
}

func (q *Queries) CreateMain(ctx context.Context, arg CreateMainParams) (AppMain, error) {
	row := q.db.QueryRow(ctx, createMain,
		arg.CreatorUserID,
		arg.MediaAssetID,
		arg.State,
		arg.ReviewReasonCode,
		arg.PostReportState,
		arg.PriceMinor,
		arg.CurrencyCode,
		arg.OwnershipConfirmed,
		arg.ConsentConfirmed,
		arg.ApprovedForUnlockAt,
	)
	var i AppMain
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.PriceMinor,
		&i.CurrencyCode,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.ApprovedForUnlockAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainByID = `-- name: GetMainByID :one
SELECT id, creator_user_id, media_asset_id, state, review_reason_code, post_report_state, price_minor, currency_code, ownership_confirmed, consent_confirmed, approved_for_unlock_at, created_at, updated_at
FROM app.mains
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMainByID(ctx context.Context, id pgtype.UUID) (AppMain, error) {
	row := q.db.QueryRow(ctx, getMainByID, id)
	var i AppMain
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.PriceMinor,
		&i.CurrencyCode,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.ApprovedForUnlockAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnlockableMainByID = `-- name: GetUnlockableMainByID :one
SELECT id, creator_user_id, media_asset_id, state, review_reason_code, post_report_state, price_minor, currency_code, ownership_confirmed, consent_confirmed, approved_for_unlock_at, created_at, updated_at
FROM app.unlockable_mains
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUnlockableMainByID(ctx context.Context, id pgtype.UUID) (AppUnlockableMain, error) {
	row := q.db.QueryRow(ctx, getUnlockableMainByID, id)
	var i AppUnlockableMain
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.PriceMinor,
		&i.CurrencyCode,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.ApprovedForUnlockAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMainsByCreatorUserID = `-- name: ListMainsByCreatorUserID :many
SELECT id, creator_user_id, media_asset_id, state, review_reason_code, post_report_state, price_minor, currency_code, ownership_confirmed, consent_confirmed, approved_for_unlock_at, created_at, updated_at
FROM app.mains
WHERE creator_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMainsByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) ([]AppMain, error) {
	rows, err := q.db.Query(ctx, listMainsByCreatorUserID, creatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMain
	for rows.Next() {
		var i AppMain
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.PriceMinor,
			&i.CurrencyCode,
			&i.OwnershipConfirmed,
			&i.ConsentConfirmed,
			&i.ApprovedForUnlockAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMainState = `-- name: UpdateMainState :one
UPDATE app.mains
SET
    state = $1,
    review_reason_code = $2,
    post_report_state = $3,
    price_minor = $4,
    currency_code = $5,
    ownership_confirmed = $6,
    consent_confirmed = $7,
    approved_for_unlock_at = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9
RETURNING id, creator_user_id, media_asset_id, state, review_reason_code, post_report_state, price_minor, currency_code, ownership_confirmed, consent_confirmed, approved_for_unlock_at, created_at, updated_at
`

type UpdateMainStateParams struct {
	State               string
	ReviewReasonCode    pgtype.Text
	PostReportState     pgtype.Text
	PriceMinor          int64
	CurrencyCode        string
	OwnershipConfirmed  bool
	ConsentConfirmed    bool
	ApprovedForUnlockAt pgtype.Timestamptz
	ID                  pgtype.UUID
}

func (q *Queries) UpdateMainState(ctx context.Context, arg UpdateMainStateParams) (AppMain, error) {
	row := q.db.QueryRow(ctx, updateMainState,
		arg.State,
		arg.ReviewReasonCode,
		arg.PostReportState,
		arg.PriceMinor,
		arg.CurrencyCode,
		arg.OwnershipConfirmed,
		arg.ConsentConfirmed,
		arg.ApprovedForUnlockAt,
		arg.ID,
	)
	var i AppMain
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.PriceMinor,
		&i.CurrencyCode,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.ApprovedForUnlockAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
