// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: main_unlocks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMainUnlock = `-- name: CreateMainUnlock :one
INSERT INTO app.main_unlocks (
    user_id,
    main_id,
    payment_provider_purchase_ref,
    purchased_at
) VALUES (
    $1,
    $2,
    $3,
    COALESCE($4::timestamptz, CURRENT_TIMESTAMP)
)
RETURNING user_id, main_id, payment_provider_purchase_ref, purchased_at, created_at
`

type CreateMainUnlockParams struct {
	UserID                     pgtype.UUID
	MainID                     pgtype.UUID
	PaymentProviderPurchaseRef pgtype.Text
	PurchasedAt                pgtype.Timestamptz
}

func (q *Queries) CreateMainUnlock(ctx context.Context, arg CreateMainUnlockParams) (AppMainUnlock, error) {
	row := q.db.QueryRow(ctx, createMainUnlock,
		arg.UserID,
		arg.MainID,
		arg.PaymentProviderPurchaseRef,
		arg.PurchasedAt,
	)
	var i AppMainUnlock
	err := row.Scan(
		&i.UserID,
		&i.MainID,
		&i.PaymentProviderPurchaseRef,
		&i.PurchasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ensureMainUnlock = `-- name: EnsureMainUnlock :one
WITH inserted AS (
    INSERT INTO app.main_unlocks (
        user_id,
        main_id,
        payment_provider_purchase_ref,
        purchased_at
    ) VALUES (
        $1,
        $2,
        $3,
        COALESCE($4::timestamptz, CURRENT_TIMESTAMP)
    )
    ON CONFLICT (user_id, main_id) DO NOTHING
    RETURNING user_id, main_id, payment_provider_purchase_ref, purchased_at, created_at
)
SELECT user_id, main_id, payment_provider_purchase_ref, purchased_at, created_at
FROM inserted
UNION ALL
SELECT user_id, main_id, payment_provider_purchase_ref, purchased_at, created_at
FROM app.main_unlocks
WHERE NOT EXISTS (SELECT 1 FROM inserted)
    AND user_id = $1
    AND main_id = $2
LIMIT 1
`

type EnsureMainUnlockParams struct {
	UserID                     pgtype.UUID
	MainID                     pgtype.UUID
	PaymentProviderPurchaseRef pgtype.Text
	PurchasedAt                pgtype.Timestamptz
}

type EnsureMainUnlockRow struct {
	UserID                     pgtype.UUID
	MainID                     pgtype.UUID
	PaymentProviderPurchaseRef pgtype.Text
	PurchasedAt                pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
}

func (q *Queries) EnsureMainUnlock(ctx context.Context, arg EnsureMainUnlockParams) (EnsureMainUnlockRow, error) {
	row := q.db.QueryRow(ctx, ensureMainUnlock,
		arg.UserID,
		arg.MainID,
		arg.PaymentProviderPurchaseRef,
		arg.PurchasedAt,
	)
	var i EnsureMainUnlockRow
	err := row.Scan(
		&i.UserID,
		&i.MainID,
		&i.PaymentProviderPurchaseRef,
		&i.PurchasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMainUnlockByUserIDAndMainID = `-- name: GetMainUnlockByUserIDAndMainID :one
SELECT user_id, main_id, payment_provider_purchase_ref, purchased_at, created_at
FROM app.main_unlocks
WHERE user_id = $1
    AND main_id = $2
LIMIT 1
`

type GetMainUnlockByUserIDAndMainIDParams struct {
	UserID pgtype.UUID
	MainID pgtype.UUID
}

func (q *Queries) GetMainUnlockByUserIDAndMainID(ctx context.Context, arg GetMainUnlockByUserIDAndMainIDParams) (AppMainUnlock, error) {
	row := q.db.QueryRow(ctx, getMainUnlockByUserIDAndMainID, arg.UserID, arg.MainID)
	var i AppMainUnlock
	err := row.Scan(
		&i.UserID,
		&i.MainID,
		&i.PaymentProviderPurchaseRef,
		&i.PurchasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnlockedMainIDsByUserID = `-- name: ListUnlockedMainIDsByUserID :many
SELECT main_id
FROM app.main_unlocks
WHERE user_id = $1
ORDER BY purchased_at DESC, created_at DESC, main_id DESC
`

func (q *Queries) ListUnlockedMainIDsByUserID(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUnlockedMainIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var main_id pgtype.UUID
		if err := rows.Scan(&main_id); err != nil {
			return nil, err
		}
		items = append(items, main_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
