// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media_processing_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaProcessingJob = `-- name: CreateMediaProcessingJob :one
INSERT INTO app.media_processing_jobs (
    creator_user_id,
    media_asset_id,
    asset_role,
    status,
    attempt_count,
    last_error_code,
    last_error_message,
    started_at,
    completed_at,
    failed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, creator_user_id, media_asset_id, asset_role, status, attempt_count, last_error_code, last_error_message, queued_at, started_at, completed_at, failed_at, created_at, updated_at
`

type CreateMediaProcessingJobParams struct {
	CreatorUserID    pgtype.UUID
	MediaAssetID     pgtype.UUID
	AssetRole        string
	Status           string
	AttemptCount     int32
	LastErrorCode    pgtype.Text
	LastErrorMessage pgtype.Text
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
}

func (q *Queries) CreateMediaProcessingJob(ctx context.Context, arg CreateMediaProcessingJobParams) (AppMediaProcessingJob, error) {
	row := q.db.QueryRow(ctx, createMediaProcessingJob,
		arg.CreatorUserID,
		arg.MediaAssetID,
		arg.AssetRole,
		arg.Status,
		arg.AttemptCount,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
	)
	var i AppMediaProcessingJob
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.AssetRole,
		&i.Status,
		&i.AttemptCount,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
