// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media_assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO app.media_assets (
    creator_user_id,
    processing_state,
    storage_provider,
    storage_bucket,
    storage_key,
    playback_url,
    mime_type,
    duration_ms,
    external_upload_ref
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, creator_user_id, processing_state, storage_provider, storage_bucket, storage_key, playback_url, mime_type, duration_ms, external_upload_ref, created_at, updated_at
`

type CreateMediaAssetParams struct {
	CreatorUserID     pgtype.UUID
	ProcessingState   string
	StorageProvider   string
	StorageBucket     string
	StorageKey        string
	PlaybackUrl       pgtype.Text
	MimeType          string
	DurationMs        pgtype.Int8
	ExternalUploadRef pgtype.Text
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (AppMediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.CreatorUserID,
		arg.ProcessingState,
		arg.StorageProvider,
		arg.StorageBucket,
		arg.StorageKey,
		arg.PlaybackUrl,
		arg.MimeType,
		arg.DurationMs,
		arg.ExternalUploadRef,
	)
	var i AppMediaAsset
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.ProcessingState,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StorageKey,
		&i.PlaybackUrl,
		&i.MimeType,
		&i.DurationMs,
		&i.ExternalUploadRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT id, creator_user_id, processing_state, storage_provider, storage_bucket, storage_key, playback_url, mime_type, duration_ms, external_upload_ref, created_at, updated_at
FROM app.media_assets
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id pgtype.UUID) (AppMediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByID, id)
	var i AppMediaAsset
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.ProcessingState,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StorageKey,
		&i.PlaybackUrl,
		&i.MimeType,
		&i.DurationMs,
		&i.ExternalUploadRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaAssetsByCreatorUserID = `-- name: ListMediaAssetsByCreatorUserID :many
SELECT id, creator_user_id, processing_state, storage_provider, storage_bucket, storage_key, playback_url, mime_type, duration_ms, external_upload_ref, created_at, updated_at
FROM app.media_assets
WHERE creator_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMediaAssetsByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) ([]AppMediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssetsByCreatorUserID, creatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMediaAsset
	for rows.Next() {
		var i AppMediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.ProcessingState,
			&i.StorageProvider,
			&i.StorageBucket,
			&i.StorageKey,
			&i.PlaybackUrl,
			&i.MimeType,
			&i.DurationMs,
			&i.ExternalUploadRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaAssetProcessingState = `-- name: UpdateMediaAssetProcessingState :one
UPDATE app.media_assets
SET
    processing_state = $1,
    playback_url = $2,
    duration_ms = $3,
    external_upload_ref = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, creator_user_id, processing_state, storage_provider, storage_bucket, storage_key, playback_url, mime_type, duration_ms, external_upload_ref, created_at, updated_at
`

type UpdateMediaAssetProcessingStateParams struct {
	ProcessingState   string
	PlaybackUrl       pgtype.Text
	DurationMs        pgtype.Int8
	ExternalUploadRef pgtype.Text
	ID                pgtype.UUID
}

func (q *Queries) UpdateMediaAssetProcessingState(ctx context.Context, arg UpdateMediaAssetProcessingStateParams) (AppMediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaAssetProcessingState,
		arg.ProcessingState,
		arg.PlaybackUrl,
		arg.DurationMs,
		arg.ExternalUploadRef,
		arg.ID,
	)
	var i AppMediaAsset
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.ProcessingState,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StorageKey,
		&i.PlaybackUrl,
		&i.MimeType,
		&i.DurationMs,
		&i.ExternalUploadRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
