// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuthIdentity struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Provider            string
	ProviderSubject     string
	EmailNormalized     pgtype.Text
	VerifiedAt          pgtype.Timestamptz
	LastAuthenticatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AppAuthLoginChallenge struct {
	ID                 pgtype.UUID
	Provider           string
	ProviderSubject    string
	EmailNormalized    pgtype.Text
	ChallengeTokenHash string
	Purpose            string
	ExpiresAt          pgtype.Timestamptz
	ConsumedAt         pgtype.Timestamptz
	AttemptCount       int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AppAuthSession struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	ActiveMode            string
	SessionTokenHash      string
	ExpiresAt             pgtype.Timestamptz
	LastSeenAt            pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RecentAuthenticatedAt pgtype.Timestamptz
}

type AppCreatorCapability struct {
	UserID                   pgtype.UUID
	State                    string
	RejectionReasonCode      pgtype.Text
	IsResubmitEligible       bool
	IsSupportReviewRequired  bool
	SelfServeResubmitCount   int32
	KycProviderCaseRef       pgtype.Text
	PayoutProviderAccountRef pgtype.Text
	SubmittedAt              pgtype.Timestamptz
	ApprovedAt               pgtype.Timestamptz
	RejectedAt               pgtype.Timestamptz
	SuspendedAt              pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type AppCreatorFollow struct {
	UserID        pgtype.UUID
	CreatorUserID pgtype.UUID
	FollowedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type AppCreatorProfile struct {
	UserID      pgtype.UUID
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	Bio         string
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Handle      string
}

type AppCreatorRegistrationEvidence struct {
	UserID        pgtype.UUID
	Kind          string
	FileName      string
	MimeType      string
	FileSizeBytes int64
	StorageBucket string
	StorageKey    string
	UploadedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AppCreatorRegistrationIntake struct {
	UserID                       pgtype.UUID
	LegalName                    string
	BirthDate                    pgtype.Date
	PayoutRecipientType          pgtype.Text
	PayoutRecipientName          string
	DeclaresNoProhibitedCategory bool
	AcceptsConsentResponsibility bool
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type AppMain struct {
	ID                  pgtype.UUID
	CreatorUserID       pgtype.UUID
	MediaAssetID        pgtype.UUID
	State               string
	ReviewReasonCode    pgtype.Text
	PostReportState     pgtype.Text
	PriceMinor          int64
	CurrencyCode        string
	OwnershipConfirmed  bool
	ConsentConfirmed    bool
	ApprovedForUnlockAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AppMainPlaybackProgress struct {
	UserID         pgtype.UUID
	MainID         pgtype.UUID
	LastPositionMs int64
	LastPlayedAt   pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AppMainPurchaseAttempt struct {
	ID                       pgtype.UUID
	UserID                   pgtype.UUID
	MainID                   pgtype.UUID
	FromShortID              pgtype.UUID
	Provider                 string
	PaymentMethodMode        string
	UserPaymentMethodID      pgtype.UUID
	ProviderPaymentTokenRef  string
	IdempotencyKey           string
	Status                   string
	FailureReason            pgtype.Text
	PendingReason            pgtype.Text
	ProviderPurchaseRef      pgtype.Text
	ProviderTransactionRef   pgtype.Text
	ProviderSessionRef       pgtype.Text
	ProviderPaymentUniqueRef pgtype.Text
	ProviderDeclineCode      pgtype.Int4
	ProviderDeclineText      pgtype.Text
	RequestedPriceJpy        int64
	RequestedCurrencyCode    int32
	AcceptedAge              bool
	AcceptedTerms            bool
	ProviderProcessedAt      pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type AppMainUnlock struct {
	UserID                     pgtype.UUID
	MainID                     pgtype.UUID
	PaymentProviderPurchaseRef pgtype.Text
	PurchasedAt                pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
}

type AppMediaAsset struct {
	ID                pgtype.UUID
	CreatorUserID     pgtype.UUID
	ProcessingState   string
	StorageProvider   string
	StorageBucket     string
	StorageKey        string
	PlaybackUrl       pgtype.Text
	MimeType          string
	DurationMs        pgtype.Int8
	ExternalUploadRef pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AppMediaProcessingJob struct {
	ID               pgtype.UUID
	CreatorUserID    pgtype.UUID
	MediaAssetID     pgtype.UUID
	AssetRole        string
	Status           string
	AttemptCount     int32
	LastErrorCode    pgtype.Text
	LastErrorMessage pgtype.Text
	QueuedAt         pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	FailedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AppPinnedShort struct {
	UserID    pgtype.UUID
	ShortID   pgtype.UUID
	PinnedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AppPublicCreatorProfile struct {
	UserID      pgtype.UUID
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	Bio         string
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Handle      string
}

type AppPublicShort struct {
	ID                   pgtype.UUID
	CreatorUserID        pgtype.UUID
	CanonicalMainID      pgtype.UUID
	MediaAssetID         pgtype.UUID
	Caption              pgtype.Text
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	ApprovedForPublishAt pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AppRecommendationEvent struct {
	ID              pgtype.UUID
	ViewerUserID    pgtype.UUID
	EventKind       string
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	ShortID         pgtype.UUID
	OccurredAt      pgtype.Timestamptz
	IdempotencyKey  string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AppRecommendationShortGlobalFeature struct {
	ShortID                pgtype.UUID
	CreatorUserID          pgtype.UUID
	CanonicalMainID        pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type AppRecommendationViewerCreatorFeature struct {
	ViewerUserID           pgtype.UUID
	CreatorUserID          pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	ProfileClickCount      int64
	LastProfileClickAt     pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type AppRecommendationViewerMainFeature struct {
	ViewerUserID           pgtype.UUID
	CanonicalMainID        pgtype.UUID
	CreatorUserID          pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type AppRecommendationViewerShortFeature struct {
	ViewerUserID           pgtype.UUID
	ShortID                pgtype.UUID
	CreatorUserID          pgtype.UUID
	CanonicalMainID        pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type AppShort struct {
	ID                   pgtype.UUID
	CreatorUserID        pgtype.UUID
	CanonicalMainID      pgtype.UUID
	MediaAssetID         pgtype.UUID
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	ApprovedForPublishAt pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Caption              pgtype.Text
}

type AppUnlockableMain struct {
	ID                  pgtype.UUID
	CreatorUserID       pgtype.UUID
	MediaAssetID        pgtype.UUID
	State               string
	ReviewReasonCode    pgtype.Text
	PostReportState     pgtype.Text
	PriceMinor          pgtype.Int8
	CurrencyCode        pgtype.Text
	OwnershipConfirmed  bool
	ConsentConfirmed    bool
	ApprovedForUnlockAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type AppUser struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppUserPaymentMethod struct {
	ID                        pgtype.UUID
	UserID                    pgtype.UUID
	Provider                  string
	ProviderPaymentTokenRef   string
	ProviderPaymentAccountRef string
	Brand                     string
	Last4                     string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	LastUsedAt                pgtype.Timestamptz
}

type AppUserProfile struct {
	UserID      pgtype.UUID
	DisplayName string
	Handle      string
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
