// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: overview.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreatorFollowsByUserID = `-- name: CountCreatorFollowsByUserID :one
SELECT COUNT(*)::bigint
FROM app.creator_follows
WHERE user_id = $1
`

func (q *Queries) CountCreatorFollowsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCreatorFollowsByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPinnedShortsByUserID = `-- name: CountPinnedShortsByUserID :one
SELECT COUNT(*)::bigint
FROM app.pinned_shorts
WHERE user_id = $1
`

func (q *Queries) CountPinnedShortsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPinnedShortsByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnlockedMainsByUserID = `-- name: CountUnlockedMainsByUserID :one
SELECT COUNT(*)::bigint
FROM app.main_unlocks
WHERE user_id = $1
`

func (q *Queries) CountUnlockedMainsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnlockedMainsByUserID, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
