// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_methods.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPaymentMethodByIDAndUserID = `-- name: GetUserPaymentMethodByIDAndUserID :one
SELECT id, user_id, provider, provider_payment_token_ref, provider_payment_account_ref, brand, last4, created_at, updated_at, last_used_at
FROM app.user_payment_methods
WHERE id = $1
    AND user_id = $2
LIMIT 1
`

type GetUserPaymentMethodByIDAndUserIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetUserPaymentMethodByIDAndUserID(ctx context.Context, arg GetUserPaymentMethodByIDAndUserIDParams) (AppUserPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getUserPaymentMethodByIDAndUserID, arg.ID, arg.UserID)
	var i AppUserPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderPaymentTokenRef,
		&i.ProviderPaymentAccountRef,
		&i.Brand,
		&i.Last4,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listUserPaymentMethodsByUserID = `-- name: ListUserPaymentMethodsByUserID :many
SELECT id, user_id, provider, provider_payment_token_ref, provider_payment_account_ref, brand, last4, created_at, updated_at, last_used_at
FROM app.user_payment_methods
WHERE user_id = $1
ORDER BY last_used_at DESC, id DESC
`

func (q *Queries) ListUserPaymentMethodsByUserID(ctx context.Context, userID pgtype.UUID) ([]AppUserPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listUserPaymentMethodsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUserPaymentMethod
	for rows.Next() {
		var i AppUserPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderPaymentTokenRef,
			&i.ProviderPaymentAccountRef,
			&i.Brand,
			&i.Last4,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserPaymentMethodLastUsedAt = `-- name: TouchUserPaymentMethodLastUsedAt :one
UPDATE app.user_payment_methods
SET last_used_at = COALESCE($1::timestamptz, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
    AND user_id = $3
RETURNING id, user_id, provider, provider_payment_token_ref, provider_payment_account_ref, brand, last4, created_at, updated_at, last_used_at
`

type TouchUserPaymentMethodLastUsedAtParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) TouchUserPaymentMethodLastUsedAt(ctx context.Context, arg TouchUserPaymentMethodLastUsedAtParams) (AppUserPaymentMethod, error) {
	row := q.db.QueryRow(ctx, touchUserPaymentMethodLastUsedAt, arg.LastUsedAt, arg.ID, arg.UserID)
	var i AppUserPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderPaymentTokenRef,
		&i.ProviderPaymentAccountRef,
		&i.Brand,
		&i.Last4,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const upsertUserPaymentMethod = `-- name: UpsertUserPaymentMethod :one
INSERT INTO app.user_payment_methods (
    user_id,
    provider,
    provider_payment_token_ref,
    provider_payment_account_ref,
    brand,
    last4,
    last_used_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    COALESCE($7::timestamptz, CURRENT_TIMESTAMP)
)
ON CONFLICT (user_id, provider_payment_account_ref) DO UPDATE
SET provider_payment_token_ref = EXCLUDED.provider_payment_token_ref,
    brand = EXCLUDED.brand,
    last4 = EXCLUDED.last4,
    last_used_at = EXCLUDED.last_used_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, provider, provider_payment_token_ref, provider_payment_account_ref, brand, last4, created_at, updated_at, last_used_at
`

type UpsertUserPaymentMethodParams struct {
	UserID                    pgtype.UUID
	Provider                  string
	ProviderPaymentTokenRef   string
	ProviderPaymentAccountRef string
	Brand                     string
	Last4                     string
	LastUsedAt                pgtype.Timestamptz
}

func (q *Queries) UpsertUserPaymentMethod(ctx context.Context, arg UpsertUserPaymentMethodParams) (AppUserPaymentMethod, error) {
	row := q.db.QueryRow(ctx, upsertUserPaymentMethod,
		arg.UserID,
		arg.Provider,
		arg.ProviderPaymentTokenRef,
		arg.ProviderPaymentAccountRef,
		arg.Brand,
		arg.Last4,
		arg.LastUsedAt,
	)
	var i AppUserPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderPaymentTokenRef,
		&i.ProviderPaymentAccountRef,
		&i.Brand,
		&i.Last4,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
