// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pinned_shorts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFanProfilePinnedShortItems = `-- name: ListFanProfilePinnedShortItems :many
SELECT
    pinned.short_id,
    pinned.pinned_at,
    short.creator_user_id,
    short.canonical_main_id,
    short.media_asset_id,
    short.caption,
    media.duration_ms,
    profile.display_name,
    profile.handle,
    profile.avatar_url,
    profile.bio
FROM app.pinned_shorts AS pinned
JOIN app.public_shorts AS short
    ON short.id = pinned.short_id
JOIN app.media_assets AS media
    ON media.id = short.media_asset_id
JOIN app.public_creator_profiles AS profile
    ON profile.user_id = short.creator_user_id
WHERE pinned.user_id = $1
AND (
    $2::timestamptz IS NULL
    OR pinned.pinned_at < $2::timestamptz
    OR (
        pinned.pinned_at = $2::timestamptz
        AND pinned.short_id < COALESCE(
            $3::uuid,
            'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid
        )
    )
)
ORDER BY pinned.pinned_at DESC, pinned.short_id DESC
LIMIT $4
`

type ListFanProfilePinnedShortItemsParams struct {
	UserID         pgtype.UUID
	CursorPinnedAt pgtype.Timestamptz
	CursorShortID  pgtype.UUID
	LimitCount     int32
}

type ListFanProfilePinnedShortItemsRow struct {
	ShortID         pgtype.UUID
	PinnedAt        pgtype.Timestamptz
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	MediaAssetID    pgtype.UUID
	Caption         pgtype.Text
	DurationMs      pgtype.Int8
	DisplayName     pgtype.Text
	Handle          string
	AvatarUrl       pgtype.Text
	Bio             string
}

func (q *Queries) ListFanProfilePinnedShortItems(ctx context.Context, arg ListFanProfilePinnedShortItemsParams) ([]ListFanProfilePinnedShortItemsRow, error) {
	rows, err := q.db.Query(ctx, listFanProfilePinnedShortItems,
		arg.UserID,
		arg.CursorPinnedAt,
		arg.CursorShortID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFanProfilePinnedShortItemsRow
	for rows.Next() {
		var i ListFanProfilePinnedShortItemsRow
		if err := rows.Scan(
			&i.ShortID,
			&i.PinnedAt,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.DurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
