// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: public_shorts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicShortDetailItem = `-- name: GetPublicShortDetailItem :one
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.pinned_shorts AS pinned
            WHERE pinned.user_id = $1::uuid
                AND pinned.short_id = s.id
        )
    END AS is_pinned,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.main_unlocks AS main_unlock
            WHERE main_unlock.user_id = $1::uuid
                AND main_unlock.main_id = s.canonical_main_id
        )
    END AS is_unlocked,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE $1::uuid = s.creator_user_id
    END AS is_owner,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.creator_follows AS creator_follow
            WHERE creator_follow.user_id = $1::uuid
                AND creator_follow.creator_user_id = s.creator_user_id
        )
    END AS is_following_creator
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
WHERE s.id = $2
LIMIT 1
`

type GetPublicShortDetailItemParams struct {
	ViewerUserID pgtype.UUID
	ShortID      pgtype.UUID
}

type GetPublicShortDetailItemRow struct {
	ID                 pgtype.UUID
	CreatorUserID      pgtype.UUID
	CanonicalMainID    pgtype.UUID
	MediaAssetID       pgtype.UUID
	Caption            pgtype.Text
	PublishedAt        pgtype.Timestamptz
	ShortDurationMs    pgtype.Int8
	DisplayName        pgtype.Text
	Handle             string
	AvatarUrl          pgtype.Text
	Bio                string
	MainPriceMinor     pgtype.Int8
	MainDurationMs     pgtype.Int8
	IsPinned           interface{}
	IsUnlocked         interface{}
	IsOwner            interface{}
	IsFollowingCreator interface{}
}

func (q *Queries) GetPublicShortDetailItem(ctx context.Context, arg GetPublicShortDetailItemParams) (GetPublicShortDetailItemRow, error) {
	row := q.db.QueryRow(ctx, getPublicShortDetailItem, arg.ViewerUserID, arg.ShortID)
	var i GetPublicShortDetailItemRow
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.Caption,
		&i.PublishedAt,
		&i.ShortDurationMs,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.Bio,
		&i.MainPriceMinor,
		&i.MainDurationMs,
		&i.IsPinned,
		&i.IsUnlocked,
		&i.IsOwner,
		&i.IsFollowingCreator,
	)
	return i, err
}

const listFollowingPublicFeedItems = `-- name: ListFollowingPublicFeedItems :many
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    EXISTS (
        SELECT 1
        FROM app.pinned_shorts AS pinned
        WHERE pinned.user_id = $1
            AND pinned.short_id = s.id
    ) AS is_pinned,
    EXISTS (
        SELECT 1
        FROM app.main_unlocks AS main_unlock
        WHERE main_unlock.user_id = $1
            AND main_unlock.main_id = s.canonical_main_id
    ) AS is_unlocked,
    $1 = s.creator_user_id AS is_owner
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
JOIN app.creator_follows AS followed_creator
    ON followed_creator.user_id = $1
    AND followed_creator.creator_user_id = s.creator_user_id
WHERE (
    $2::timestamptz IS NULL
    OR s.published_at < $2::timestamptz
    OR (
        s.published_at = $2::timestamptz
        AND s.id < COALESCE($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)
    )
)
ORDER BY s.published_at DESC, s.id DESC
LIMIT $4
`

type ListFollowingPublicFeedItemsParams struct {
	ViewerUserID      pgtype.UUID
	CursorPublishedAt pgtype.Timestamptz
	CursorShortID     pgtype.UUID
	LimitCount        int32
}

type ListFollowingPublicFeedItemsRow struct {
	ID              pgtype.UUID
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	MediaAssetID    pgtype.UUID
	Caption         pgtype.Text
	PublishedAt     pgtype.Timestamptz
	ShortDurationMs pgtype.Int8
	DisplayName     pgtype.Text
	Handle          string
	AvatarUrl       pgtype.Text
	Bio             string
	MainPriceMinor  pgtype.Int8
	MainDurationMs  pgtype.Int8
	IsPinned        bool
	IsUnlocked      bool
	IsOwner         bool
}

func (q *Queries) ListFollowingPublicFeedItems(ctx context.Context, arg ListFollowingPublicFeedItemsParams) ([]ListFollowingPublicFeedItemsRow, error) {
	rows, err := q.db.Query(ctx, listFollowingPublicFeedItems,
		arg.ViewerUserID,
		arg.CursorPublishedAt,
		arg.CursorShortID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingPublicFeedItemsRow
	for rows.Next() {
		var i ListFollowingPublicFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.PublishedAt,
			&i.ShortDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.MainPriceMinor,
			&i.MainDurationMs,
			&i.IsPinned,
			&i.IsUnlocked,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendedPublicFeedItems = `-- name: ListRecommendedPublicFeedItems :many
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.pinned_shorts AS pinned
            WHERE pinned.user_id = $1::uuid
                AND pinned.short_id = s.id
        )
    END AS is_pinned,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.main_unlocks AS main_unlock
            WHERE main_unlock.user_id = $1::uuid
                AND main_unlock.main_id = s.canonical_main_id
        )
    END AS is_unlocked,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE $1::uuid = s.creator_user_id
    END AS is_owner
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
WHERE (
    $2::timestamptz IS NULL
    OR s.published_at < $2::timestamptz
    OR (
        s.published_at = $2::timestamptz
        AND s.id < COALESCE($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)
    )
)
ORDER BY s.published_at DESC, s.id DESC
LIMIT $4
`

type ListRecommendedPublicFeedItemsParams struct {
	ViewerUserID      pgtype.UUID
	CursorPublishedAt pgtype.Timestamptz
	CursorShortID     pgtype.UUID
	LimitCount        int32
}

type ListRecommendedPublicFeedItemsRow struct {
	ID              pgtype.UUID
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	MediaAssetID    pgtype.UUID
	Caption         pgtype.Text
	PublishedAt     pgtype.Timestamptz
	ShortDurationMs pgtype.Int8
	DisplayName     pgtype.Text
	Handle          string
	AvatarUrl       pgtype.Text
	Bio             string
	MainPriceMinor  pgtype.Int8
	MainDurationMs  pgtype.Int8
	IsPinned        interface{}
	IsUnlocked      interface{}
	IsOwner         interface{}
}

func (q *Queries) ListRecommendedPublicFeedItems(ctx context.Context, arg ListRecommendedPublicFeedItemsParams) ([]ListRecommendedPublicFeedItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendedPublicFeedItems,
		arg.ViewerUserID,
		arg.CursorPublishedAt,
		arg.CursorShortID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendedPublicFeedItemsRow
	for rows.Next() {
		var i ListRecommendedPublicFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.PublishedAt,
			&i.ShortDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.MainPriceMinor,
			&i.MainDurationMs,
			&i.IsPinned,
			&i.IsUnlocked,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
