// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: public_shorts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicShortDetailItem = `-- name: GetPublicShortDetailItem :one
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.pinned_shorts AS pinned
            WHERE pinned.user_id = $1::uuid
                AND pinned.short_id = s.id
        )
    END AS is_pinned,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.main_unlocks AS main_unlock
            WHERE main_unlock.user_id = $1::uuid
                AND main_unlock.main_id = s.canonical_main_id
        )
    END AS is_unlocked,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE $1::uuid = s.creator_user_id
    END AS is_owner,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.creator_follows AS creator_follow
            WHERE creator_follow.user_id = $1::uuid
                AND creator_follow.creator_user_id = s.creator_user_id
        )
    END AS is_following_creator
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
WHERE s.id = $2
LIMIT 1
`

type GetPublicShortDetailItemParams struct {
	ViewerUserID pgtype.UUID
	ShortID      pgtype.UUID
}

type GetPublicShortDetailItemRow struct {
	ID                 pgtype.UUID
	CreatorUserID      pgtype.UUID
	CanonicalMainID    pgtype.UUID
	MediaAssetID       pgtype.UUID
	Caption            pgtype.Text
	PublishedAt        pgtype.Timestamptz
	ShortDurationMs    pgtype.Int8
	DisplayName        pgtype.Text
	Handle             string
	AvatarUrl          pgtype.Text
	Bio                string
	MainPriceMinor     int64
	MainDurationMs     pgtype.Int8
	IsPinned           interface{}
	IsUnlocked         interface{}
	IsOwner            interface{}
	IsFollowingCreator interface{}
}

func (q *Queries) GetPublicShortDetailItem(ctx context.Context, arg GetPublicShortDetailItemParams) (GetPublicShortDetailItemRow, error) {
	row := q.db.QueryRow(ctx, getPublicShortDetailItem, arg.ViewerUserID, arg.ShortID)
	var i GetPublicShortDetailItemRow
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.Caption,
		&i.PublishedAt,
		&i.ShortDurationMs,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.Bio,
		&i.MainPriceMinor,
		&i.MainDurationMs,
		&i.IsPinned,
		&i.IsUnlocked,
		&i.IsOwner,
		&i.IsFollowingCreator,
	)
	return i, err
}

const listFeedItemsByShortIDs = `-- name: ListFeedItemsByShortIDs :many
WITH snapshot_short_ids AS (
    SELECT
        ordered_short_ids.short_id,
        ordered_short_ids.ordinality
    FROM unnest($2::uuid[]) WITH ORDINALITY AS ordered_short_ids(short_id, ordinality)
)
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.pinned_shorts AS pinned
            WHERE pinned.user_id = $1::uuid
                AND pinned.short_id = s.id
        )
    END AS is_pinned,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.main_unlocks AS main_unlock
            WHERE main_unlock.user_id = $1::uuid
                AND main_unlock.main_id = s.canonical_main_id
        )
    END AS is_unlocked,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE $1::uuid = s.creator_user_id
    END AS is_owner,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.creator_follows AS creator_follow
            WHERE creator_follow.user_id = $1::uuid
                AND creator_follow.creator_user_id = s.creator_user_id
        )
    END AS is_following_creator
FROM snapshot_short_ids
JOIN app.public_shorts AS s
    ON s.id = snapshot_short_ids.short_id
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
ORDER BY snapshot_short_ids.ordinality ASC
`

type ListFeedItemsByShortIDsParams struct {
	ViewerUserID pgtype.UUID
	ShortIds     []pgtype.UUID
}

type ListFeedItemsByShortIDsRow struct {
	ID                 pgtype.UUID
	CreatorUserID      pgtype.UUID
	CanonicalMainID    pgtype.UUID
	MediaAssetID       pgtype.UUID
	Caption            pgtype.Text
	PublishedAt        pgtype.Timestamptz
	ShortDurationMs    pgtype.Int8
	DisplayName        pgtype.Text
	Handle             string
	AvatarUrl          pgtype.Text
	Bio                string
	MainPriceMinor     int64
	MainDurationMs     pgtype.Int8
	IsPinned           interface{}
	IsUnlocked         interface{}
	IsOwner            interface{}
	IsFollowingCreator interface{}
}

func (q *Queries) ListFeedItemsByShortIDs(ctx context.Context, arg ListFeedItemsByShortIDsParams) ([]ListFeedItemsByShortIDsRow, error) {
	rows, err := q.db.Query(ctx, listFeedItemsByShortIDs, arg.ViewerUserID, arg.ShortIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedItemsByShortIDsRow
	for rows.Next() {
		var i ListFeedItemsByShortIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.PublishedAt,
			&i.ShortDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.MainPriceMinor,
			&i.MainDurationMs,
			&i.IsPinned,
			&i.IsUnlocked,
			&i.IsOwner,
			&i.IsFollowingCreator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingPublicFeedItems = `-- name: ListFollowingPublicFeedItems :many
WITH ranking_context AS (
    SELECT COALESCE(
        $1::timestamptz,
        DATE_TRUNC('hour', CURRENT_TIMESTAMP)
    ) AS reference_at
),
ranking_weights AS (
    SELECT
        2000000::bigint AS unlocked_main_penalty,
        900000::bigint AS seen_completion_penalty,
        180000::bigint AS rewatch_penalty,
        350000::bigint AS main_unlock_weight,
        90000::bigint AS main_click_weight,
        40000::bigint AS main_completion_weight,
        20000::bigint AS main_rewatch_weight,
        180000::bigint AS creator_unlock_weight,
        50000::bigint AS creator_main_click_weight,
        25000::bigint AS creator_profile_click_weight,
        12000::bigint AS creator_completion_weight,
        6000::bigint AS creator_rewatch_weight,
        7000::bigint AS global_unlock_weight,
        1800::bigint AS global_main_click_weight,
        900::bigint AS global_completion_weight,
        450::bigint AS global_rewatch_weight,
        120::bigint AS freshness_per_hour_weight,
        60000::bigint AS same_creator_penalty,
        120000::bigint AS same_main_penalty
),
candidate_following AS (
    SELECT
        s.id,
        s.creator_user_id,
        s.canonical_main_id,
        s.media_asset_id,
        s.caption,
        s.published_at,
        short_media.duration_ms AS short_duration_ms,
        creator_profile.display_name,
        creator_profile.handle,
        creator_profile.avatar_url,
        creator_profile.bio,
        main_record.price_minor AS main_price_minor,
        main_media.duration_ms AS main_duration_ms,
        pinned.short_id IS NOT NULL AS is_pinned,
        unlocked.main_id IS NOT NULL AS is_unlocked,
        $2 = s.creator_user_id AS is_owner,
        TRUE AS is_following_creator,
        COALESCE(viewer_short.view_completion_count, 0) AS viewer_short_view_completion_count,
        COALESCE(viewer_short.rewatch_loop_count, 0) AS viewer_short_rewatch_loop_count,
        COALESCE(viewer_creator.unlock_conversion_count, 0) AS viewer_creator_unlock_conversion_count,
        COALESCE(viewer_creator.main_click_count, 0) AS viewer_creator_main_click_count,
        COALESCE(viewer_creator.profile_click_count, 0) AS viewer_creator_profile_click_count,
        COALESCE(viewer_creator.view_completion_count, 0) AS viewer_creator_view_completion_count,
        COALESCE(viewer_creator.rewatch_loop_count, 0) AS viewer_creator_rewatch_loop_count,
        COALESCE(viewer_main.unlock_conversion_count, 0) AS viewer_main_unlock_conversion_count,
        COALESCE(viewer_main.main_click_count, 0) AS viewer_main_main_click_count,
        COALESCE(viewer_main.view_completion_count, 0) AS viewer_main_view_completion_count,
        COALESCE(viewer_main.rewatch_loop_count, 0) AS viewer_main_view_rewatch_loop_count,
        COALESCE(short_global.unlock_conversion_count, 0) AS short_global_unlock_conversion_count,
        COALESCE(short_global.main_click_count, 0) AS short_global_main_click_count,
        COALESCE(short_global.view_completion_count, 0) AS short_global_view_completion_count,
        COALESCE(short_global.rewatch_loop_count, 0) AS short_global_rewatch_loop_count
    FROM app.public_shorts AS s
    CROSS JOIN ranking_context
    JOIN app.media_assets AS short_media
        ON short_media.id = s.media_asset_id
    JOIN app.creator_profiles AS creator_profile
        ON creator_profile.user_id = s.creator_user_id
    JOIN app.unlockable_mains AS main_record
        ON main_record.id = s.canonical_main_id
    JOIN app.media_assets AS main_media
        ON main_media.id = main_record.media_asset_id
    JOIN app.creator_follows AS followed_creator
        ON followed_creator.user_id = $2
        AND followed_creator.creator_user_id = s.creator_user_id
    LEFT JOIN app.pinned_shorts AS pinned
        ON pinned.user_id = $2
        AND pinned.short_id = s.id
    LEFT JOIN app.main_unlocks AS unlocked
        ON unlocked.user_id = $2
        AND unlocked.main_id = s.canonical_main_id
    LEFT JOIN app.recommendation_viewer_short_features AS viewer_short
        ON viewer_short.viewer_user_id = $2
        AND viewer_short.short_id = s.id
    LEFT JOIN app.recommendation_viewer_creator_features AS viewer_creator
        ON viewer_creator.viewer_user_id = $2
        AND viewer_creator.creator_user_id = s.creator_user_id
    LEFT JOIN app.recommendation_viewer_main_features AS viewer_main
        ON viewer_main.viewer_user_id = $2
        AND viewer_main.canonical_main_id = s.canonical_main_id
    LEFT JOIN app.recommendation_short_global_features AS short_global
        ON short_global.short_id = s.id
    WHERE s.published_at <= ranking_context.reference_at
),
scored_following AS (
    SELECT
        candidate_following.id, candidate_following.creator_user_id, candidate_following.canonical_main_id, candidate_following.media_asset_id, candidate_following.caption, candidate_following.published_at, candidate_following.short_duration_ms, candidate_following.display_name, candidate_following.handle, candidate_following.avatar_url, candidate_following.bio, candidate_following.main_price_minor, candidate_following.main_duration_ms, candidate_following.is_pinned, candidate_following.is_unlocked, candidate_following.is_owner, candidate_following.is_following_creator, candidate_following.viewer_short_view_completion_count, candidate_following.viewer_short_rewatch_loop_count, candidate_following.viewer_creator_unlock_conversion_count, candidate_following.viewer_creator_main_click_count, candidate_following.viewer_creator_profile_click_count, candidate_following.viewer_creator_view_completion_count, candidate_following.viewer_creator_rewatch_loop_count, candidate_following.viewer_main_unlock_conversion_count, candidate_following.viewer_main_main_click_count, candidate_following.viewer_main_view_completion_count, candidate_following.viewer_main_view_rewatch_loop_count, candidate_following.short_global_unlock_conversion_count, candidate_following.short_global_main_click_count, candidate_following.short_global_view_completion_count, candidate_following.short_global_rewatch_loop_count,
        (
            CASE
                WHEN candidate_following.is_unlocked THEN -ranking_weights.unlocked_main_penalty
                ELSE 0
            END
            - (
                LEAST(candidate_following.viewer_short_view_completion_count, 1)
                * ranking_weights.seen_completion_penalty
            )
            - (
                LEAST(candidate_following.viewer_short_rewatch_loop_count, 1)
                * ranking_weights.rewatch_penalty
            )
            + (
                LEAST(candidate_following.viewer_main_unlock_conversion_count, 1)
                * ranking_weights.main_unlock_weight
            )
            + (
                LEAST(candidate_following.viewer_main_main_click_count, 3)
                * ranking_weights.main_click_weight
            )
            + (
                LEAST(candidate_following.viewer_main_view_completion_count, 1)
                * ranking_weights.main_completion_weight
            )
            + (
                LEAST(candidate_following.viewer_main_view_rewatch_loop_count, 3)
                * ranking_weights.main_rewatch_weight
            )
            + (
                LEAST(candidate_following.viewer_creator_unlock_conversion_count, 1)
                * ranking_weights.creator_unlock_weight
            )
            + (
                LEAST(candidate_following.viewer_creator_main_click_count, 3)
                * ranking_weights.creator_main_click_weight
            )
            + (
                LEAST(candidate_following.viewer_creator_profile_click_count, 3)
                * ranking_weights.creator_profile_click_weight
            )
            + (
                LEAST(candidate_following.viewer_creator_view_completion_count, 3)
                * ranking_weights.creator_completion_weight
            )
            + (
                LEAST(candidate_following.viewer_creator_rewatch_loop_count, 3)
                * ranking_weights.creator_rewatch_weight
            )
            + (
                LEAST(candidate_following.short_global_unlock_conversion_count, 10)
                * ranking_weights.global_unlock_weight
            )
            + (
                LEAST(candidate_following.short_global_main_click_count, 10)
                * ranking_weights.global_main_click_weight
            )
            + (
                LEAST(candidate_following.short_global_view_completion_count, 10)
                * ranking_weights.global_completion_weight
            )
            + (
                LEAST(candidate_following.short_global_rewatch_loop_count, 10)
                * ranking_weights.global_rewatch_weight
            )
            + (
                GREATEST(
                    0::bigint,
                    72::bigint
                    - GREATEST(
                        0::bigint,
                        FLOOR(EXTRACT(EPOCH FROM (ranking_context.reference_at - candidate_following.published_at)) / 3600)::bigint
                    )
                )
                * ranking_weights.freshness_per_hour_weight
            )
        ) AS base_rank_score
    FROM candidate_following
    CROSS JOIN ranking_weights
    CROSS JOIN ranking_context
),
diversified_following AS (
    SELECT
        scored_following.id, scored_following.creator_user_id, scored_following.canonical_main_id, scored_following.media_asset_id, scored_following.caption, scored_following.published_at, scored_following.short_duration_ms, scored_following.display_name, scored_following.handle, scored_following.avatar_url, scored_following.bio, scored_following.main_price_minor, scored_following.main_duration_ms, scored_following.is_pinned, scored_following.is_unlocked, scored_following.is_owner, scored_following.is_following_creator, scored_following.viewer_short_view_completion_count, scored_following.viewer_short_rewatch_loop_count, scored_following.viewer_creator_unlock_conversion_count, scored_following.viewer_creator_main_click_count, scored_following.viewer_creator_profile_click_count, scored_following.viewer_creator_view_completion_count, scored_following.viewer_creator_rewatch_loop_count, scored_following.viewer_main_unlock_conversion_count, scored_following.viewer_main_main_click_count, scored_following.viewer_main_view_completion_count, scored_following.viewer_main_view_rewatch_loop_count, scored_following.short_global_unlock_conversion_count, scored_following.short_global_main_click_count, scored_following.short_global_view_completion_count, scored_following.short_global_rewatch_loop_count, scored_following.base_rank_score,
        ROW_NUMBER() OVER (
            PARTITION BY scored_following.creator_user_id
            ORDER BY scored_following.base_rank_score DESC, scored_following.published_at DESC, scored_following.id DESC
        ) AS creator_rank_position,
        ROW_NUMBER() OVER (
            PARTITION BY scored_following.canonical_main_id
            ORDER BY scored_following.base_rank_score DESC, scored_following.published_at DESC, scored_following.id DESC
        ) AS main_rank_position
    FROM scored_following
),
ordered_following AS (
    SELECT
        diversified_following.id,
        diversified_following.creator_user_id,
        diversified_following.canonical_main_id,
        diversified_following.media_asset_id,
        diversified_following.caption,
        diversified_following.published_at,
        diversified_following.short_duration_ms,
        diversified_following.display_name,
        diversified_following.handle,
        diversified_following.avatar_url,
        diversified_following.bio,
        diversified_following.main_price_minor,
        diversified_following.main_duration_ms,
        diversified_following.is_pinned,
        diversified_following.is_unlocked,
        diversified_following.is_owner,
        diversified_following.is_following_creator,
        (
            diversified_following.base_rank_score
            - ((diversified_following.creator_rank_position - 1) * ranking_weights.same_creator_penalty)
            - ((diversified_following.main_rank_position - 1) * ranking_weights.same_main_penalty)
        )::bigint AS rank_score
    FROM diversified_following
    CROSS JOIN ranking_weights
)
SELECT
    ordered_following.id,
    ordered_following.creator_user_id,
    ordered_following.canonical_main_id,
    ordered_following.media_asset_id,
    ordered_following.caption,
    ordered_following.published_at,
    ordered_following.short_duration_ms,
    ordered_following.display_name,
    ordered_following.handle,
    ordered_following.avatar_url,
    ordered_following.bio,
    ordered_following.main_price_minor,
    ordered_following.main_duration_ms,
    ordered_following.is_pinned,
    ordered_following.is_unlocked,
    ordered_following.is_owner,
    ordered_following.is_following_creator,
    ordered_following.rank_score
FROM ordered_following
ORDER BY ordered_following.rank_score DESC, ordered_following.published_at DESC, ordered_following.id DESC
`

type ListFollowingPublicFeedItemsParams struct {
	RankingReferenceAt pgtype.Timestamptz
	ViewerUserID       pgtype.UUID
}

type ListFollowingPublicFeedItemsRow struct {
	ID                 pgtype.UUID
	CreatorUserID      pgtype.UUID
	CanonicalMainID    pgtype.UUID
	MediaAssetID       pgtype.UUID
	Caption            pgtype.Text
	PublishedAt        pgtype.Timestamptz
	ShortDurationMs    pgtype.Int8
	DisplayName        pgtype.Text
	Handle             string
	AvatarUrl          pgtype.Text
	Bio                string
	MainPriceMinor     pgtype.Int8
	MainDurationMs     pgtype.Int8
	IsPinned           interface{}
	IsUnlocked         interface{}
	IsOwner            bool
	IsFollowingCreator bool
	RankScore          int64
}

func (q *Queries) ListFollowingPublicFeedItems(ctx context.Context, arg ListFollowingPublicFeedItemsParams) ([]ListFollowingPublicFeedItemsRow, error) {
	rows, err := q.db.Query(ctx, listFollowingPublicFeedItems, arg.RankingReferenceAt, arg.ViewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingPublicFeedItemsRow
	for rows.Next() {
		var i ListFollowingPublicFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.PublishedAt,
			&i.ShortDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.MainPriceMinor,
			&i.MainDurationMs,
			&i.IsPinned,
			&i.IsUnlocked,
			&i.IsOwner,
			&i.IsFollowingCreator,
			&i.RankScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyRecommendedPublicFeedItems = `-- name: ListLegacyRecommendedPublicFeedItems :many
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.caption,
    s.published_at,
    short_media.duration_ms AS short_duration_ms,
    creator_profile.display_name,
    creator_profile.handle,
    creator_profile.avatar_url,
    creator_profile.bio,
    main_record.price_minor AS main_price_minor,
    main_media.duration_ms AS main_duration_ms,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.pinned_shorts AS pinned
            WHERE pinned.user_id = $1::uuid
                AND pinned.short_id = s.id
        )
    END AS is_pinned,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.main_unlocks AS main_unlock
            WHERE main_unlock.user_id = $1::uuid
                AND main_unlock.main_id = s.canonical_main_id
        )
    END AS is_unlocked,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE $1::uuid = s.creator_user_id
    END AS is_owner,
    CASE
        WHEN $1::uuid IS NULL THEN FALSE
        ELSE EXISTS (
            SELECT 1
            FROM app.creator_follows AS creator_follow
            WHERE creator_follow.user_id = $1::uuid
                AND creator_follow.creator_user_id = s.creator_user_id
        )
    END AS is_following_creator
FROM app.public_shorts AS s
JOIN app.media_assets AS short_media
    ON short_media.id = s.media_asset_id
JOIN app.creator_profiles AS creator_profile
    ON creator_profile.user_id = s.creator_user_id
JOIN app.unlockable_mains AS main_record
    ON main_record.id = s.canonical_main_id
JOIN app.media_assets AS main_media
    ON main_media.id = main_record.media_asset_id
WHERE (
    $2::timestamptz IS NULL
    OR s.published_at < $2::timestamptz
    OR (
        s.published_at = $2::timestamptz
        AND s.id < COALESCE($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)
    )
)
ORDER BY s.published_at DESC, s.id DESC
LIMIT $4
`

type ListLegacyRecommendedPublicFeedItemsParams struct {
	ViewerUserID      pgtype.UUID
	CursorPublishedAt pgtype.Timestamptz
	CursorShortID     pgtype.UUID
	LimitCount        int32
}

type ListLegacyRecommendedPublicFeedItemsRow struct {
	ID                 pgtype.UUID
	CreatorUserID      pgtype.UUID
	CanonicalMainID    pgtype.UUID
	MediaAssetID       pgtype.UUID
	Caption            pgtype.Text
	PublishedAt        pgtype.Timestamptz
	ShortDurationMs    pgtype.Int8
	DisplayName        pgtype.Text
	Handle             string
	AvatarUrl          pgtype.Text
	Bio                string
	MainPriceMinor     int64
	MainDurationMs     pgtype.Int8
	IsPinned           interface{}
	IsUnlocked         interface{}
	IsOwner            interface{}
	IsFollowingCreator interface{}
}

func (q *Queries) ListLegacyRecommendedPublicFeedItems(ctx context.Context, arg ListLegacyRecommendedPublicFeedItemsParams) ([]ListLegacyRecommendedPublicFeedItemsRow, error) {
	rows, err := q.db.Query(ctx, listLegacyRecommendedPublicFeedItems,
		arg.ViewerUserID,
		arg.CursorPublishedAt,
		arg.CursorShortID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacyRecommendedPublicFeedItemsRow
	for rows.Next() {
		var i ListLegacyRecommendedPublicFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.Caption,
			&i.PublishedAt,
			&i.ShortDurationMs,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Bio,
			&i.MainPriceMinor,
			&i.MainDurationMs,
			&i.IsPinned,
			&i.IsUnlocked,
			&i.IsOwner,
			&i.IsFollowingCreator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendedPublicFeedShortIDs = `-- name: ListRecommendedPublicFeedShortIDs :many
WITH ranking_context AS (
    SELECT COALESCE(
        $1::timestamptz,
        DATE_TRUNC('hour', CURRENT_TIMESTAMP)
    ) AS reference_at
),
ranking_weights AS (
    SELECT
        2000000::bigint AS unlocked_main_penalty,
        900000::bigint AS seen_completion_penalty,
        180000::bigint AS rewatch_penalty,
        350000::bigint AS main_unlock_weight,
        90000::bigint AS main_click_weight,
        40000::bigint AS main_completion_weight,
        20000::bigint AS main_rewatch_weight,
        180000::bigint AS creator_unlock_weight,
        50000::bigint AS creator_main_click_weight,
        25000::bigint AS creator_profile_click_weight,
        12000::bigint AS creator_completion_weight,
        6000::bigint AS creator_rewatch_weight,
        7000::bigint AS global_unlock_weight,
        1800::bigint AS global_main_click_weight,
        900::bigint AS global_completion_weight,
        450::bigint AS global_rewatch_weight,
        120::bigint AS freshness_per_hour_weight,
        60000::bigint AS same_creator_penalty,
        120000::bigint AS same_main_penalty,
        70000::bigint AS followed_creator_bonus,
        50000::bigint AS pinned_short_bonus,
        25000::bigint AS cold_candidate_bonus,
        20000::bigint AS zero_impression_exploration_bonus,
        10000::bigint AS low_impression_exploration_bonus
),
candidate_recommended_short_ids AS (
    SELECT
        s.id
    FROM app.public_shorts AS s
    CROSS JOIN ranking_context
    WHERE s.published_at <= ranking_context.reference_at
    ORDER BY s.published_at DESC, s.id DESC
    LIMIT $2
),
candidate_recommended AS (
    SELECT
        s.id,
        s.creator_user_id,
        s.canonical_main_id,
        s.media_asset_id,
        s.caption,
        s.published_at,
        short_media.duration_ms AS short_duration_ms,
        creator_profile.display_name,
        creator_profile.handle,
        creator_profile.avatar_url,
        creator_profile.bio,
        main_record.price_minor AS main_price_minor,
        main_media.duration_ms AS main_duration_ms,
        pinned.short_id IS NOT NULL AS is_pinned,
        unlocked.main_id IS NOT NULL AS is_unlocked,
        CASE
            WHEN $3::uuid IS NULL THEN FALSE
            ELSE $3::uuid = s.creator_user_id
        END AS is_owner,
        creator_follow.creator_user_id IS NOT NULL AS is_following_creator,
        COALESCE(viewer_short.view_completion_count, 0) AS viewer_short_view_completion_count,
        COALESCE(viewer_short.rewatch_loop_count, 0) AS viewer_short_rewatch_loop_count,
        COALESCE(viewer_creator.unlock_conversion_count, 0) AS viewer_creator_unlock_conversion_count,
        COALESCE(viewer_creator.main_click_count, 0) AS viewer_creator_main_click_count,
        COALESCE(viewer_creator.profile_click_count, 0) AS viewer_creator_profile_click_count,
        COALESCE(viewer_creator.view_completion_count, 0) AS viewer_creator_view_completion_count,
        COALESCE(viewer_creator.rewatch_loop_count, 0) AS viewer_creator_rewatch_loop_count,
        COALESCE(viewer_main.unlock_conversion_count, 0) AS viewer_main_unlock_conversion_count,
        COALESCE(viewer_main.main_click_count, 0) AS viewer_main_main_click_count,
        COALESCE(viewer_main.view_completion_count, 0) AS viewer_main_view_completion_count,
        COALESCE(viewer_main.rewatch_loop_count, 0) AS viewer_main_view_rewatch_loop_count,
        COALESCE(short_global.impression_count, 0) AS short_global_impression_count,
        COALESCE(short_global.unlock_conversion_count, 0) AS short_global_unlock_conversion_count,
        COALESCE(short_global.main_click_count, 0) AS short_global_main_click_count,
        COALESCE(short_global.view_completion_count, 0) AS short_global_view_completion_count,
        COALESCE(short_global.rewatch_loop_count, 0) AS short_global_view_rewatch_loop_count
    FROM candidate_recommended_short_ids
    CROSS JOIN ranking_context
    JOIN app.public_shorts AS s
        ON s.id = candidate_recommended_short_ids.id
    JOIN app.media_assets AS short_media
        ON short_media.id = s.media_asset_id
    JOIN app.creator_profiles AS creator_profile
        ON creator_profile.user_id = s.creator_user_id
    JOIN app.unlockable_mains AS main_record
        ON main_record.id = s.canonical_main_id
    JOIN app.media_assets AS main_media
        ON main_media.id = main_record.media_asset_id
    LEFT JOIN app.pinned_shorts AS pinned
        ON pinned.user_id = $3::uuid
        AND pinned.short_id = s.id
    LEFT JOIN app.main_unlocks AS unlocked
        ON unlocked.user_id = $3::uuid
        AND unlocked.main_id = s.canonical_main_id
    LEFT JOIN app.creator_follows AS creator_follow
        ON creator_follow.user_id = $3::uuid
        AND creator_follow.creator_user_id = s.creator_user_id
    LEFT JOIN app.recommendation_viewer_short_features AS viewer_short
        ON viewer_short.viewer_user_id = $3::uuid
        AND viewer_short.short_id = s.id
    LEFT JOIN app.recommendation_viewer_creator_features AS viewer_creator
        ON viewer_creator.viewer_user_id = $3::uuid
        AND viewer_creator.creator_user_id = s.creator_user_id
    LEFT JOIN app.recommendation_viewer_main_features AS viewer_main
        ON viewer_main.viewer_user_id = $3::uuid
        AND viewer_main.canonical_main_id = s.canonical_main_id
    LEFT JOIN app.recommendation_short_global_features AS short_global
        ON short_global.short_id = s.id
),
scored_recommended AS (
    SELECT
        candidate_recommended.id, candidate_recommended.creator_user_id, candidate_recommended.canonical_main_id, candidate_recommended.media_asset_id, candidate_recommended.caption, candidate_recommended.published_at, candidate_recommended.short_duration_ms, candidate_recommended.display_name, candidate_recommended.handle, candidate_recommended.avatar_url, candidate_recommended.bio, candidate_recommended.main_price_minor, candidate_recommended.main_duration_ms, candidate_recommended.is_pinned, candidate_recommended.is_unlocked, candidate_recommended.is_owner, candidate_recommended.is_following_creator, candidate_recommended.viewer_short_view_completion_count, candidate_recommended.viewer_short_rewatch_loop_count, candidate_recommended.viewer_creator_unlock_conversion_count, candidate_recommended.viewer_creator_main_click_count, candidate_recommended.viewer_creator_profile_click_count, candidate_recommended.viewer_creator_view_completion_count, candidate_recommended.viewer_creator_rewatch_loop_count, candidate_recommended.viewer_main_unlock_conversion_count, candidate_recommended.viewer_main_main_click_count, candidate_recommended.viewer_main_view_completion_count, candidate_recommended.viewer_main_view_rewatch_loop_count, candidate_recommended.short_global_impression_count, candidate_recommended.short_global_unlock_conversion_count, candidate_recommended.short_global_main_click_count, candidate_recommended.short_global_view_completion_count, candidate_recommended.short_global_view_rewatch_loop_count,
        (
            CASE
                WHEN candidate_recommended.is_unlocked THEN -ranking_weights.unlocked_main_penalty
                ELSE 0
            END
            - (
                LEAST(candidate_recommended.viewer_short_view_completion_count, 1)
                * ranking_weights.seen_completion_penalty
            )
            - (
                LEAST(candidate_recommended.viewer_short_rewatch_loop_count, 1)
                * ranking_weights.rewatch_penalty
            )
            + (
                LEAST(candidate_recommended.viewer_main_unlock_conversion_count, 1)
                * ranking_weights.main_unlock_weight
            )
            + (
                LEAST(candidate_recommended.viewer_main_main_click_count, 3)
                * ranking_weights.main_click_weight
            )
            + (
                LEAST(candidate_recommended.viewer_main_view_completion_count, 1)
                * ranking_weights.main_completion_weight
            )
            + (
                LEAST(candidate_recommended.viewer_main_view_rewatch_loop_count, 3)
                * ranking_weights.main_rewatch_weight
            )
            + (
                LEAST(candidate_recommended.viewer_creator_unlock_conversion_count, 1)
                * ranking_weights.creator_unlock_weight
            )
            + (
                LEAST(candidate_recommended.viewer_creator_main_click_count, 3)
                * ranking_weights.creator_main_click_weight
            )
            + (
                LEAST(candidate_recommended.viewer_creator_profile_click_count, 3)
                * ranking_weights.creator_profile_click_weight
            )
            + (
                LEAST(candidate_recommended.viewer_creator_view_completion_count, 3)
                * ranking_weights.creator_completion_weight
            )
            + (
                LEAST(candidate_recommended.viewer_creator_rewatch_loop_count, 3)
                * ranking_weights.creator_rewatch_weight
            )
            + (
                LEAST(candidate_recommended.short_global_unlock_conversion_count, 10)
                * ranking_weights.global_unlock_weight
            )
            + (
                LEAST(candidate_recommended.short_global_main_click_count, 10)
                * ranking_weights.global_main_click_weight
            )
            + (
                LEAST(candidate_recommended.short_global_view_completion_count, 10)
                * ranking_weights.global_completion_weight
            )
            + (
                LEAST(candidate_recommended.short_global_view_rewatch_loop_count, 10)
                * ranking_weights.global_rewatch_weight
            )
            + (
                GREATEST(
                    0::bigint,
                    72::bigint
                    - GREATEST(
                        0::bigint,
                        FLOOR(EXTRACT(EPOCH FROM (ranking_context.reference_at - candidate_recommended.published_at)) / 3600)::bigint
                    )
                )
                * ranking_weights.freshness_per_hour_weight
            )
            + (
                CASE
                    WHEN candidate_recommended.is_following_creator THEN ranking_weights.followed_creator_bonus
                    ELSE 0
                END
            )
            + (
                CASE
                    WHEN candidate_recommended.is_pinned THEN ranking_weights.pinned_short_bonus
                    ELSE 0
                END
            )
            + (
                CASE
                    WHEN candidate_recommended.short_global_impression_count = 0 THEN ranking_weights.zero_impression_exploration_bonus
                    WHEN candidate_recommended.short_global_impression_count <= 3 THEN ranking_weights.low_impression_exploration_bonus
                    ELSE 0
                END
            )
            + (
                CASE
                    WHEN $3::uuid IS NULL THEN 0
                    WHEN candidate_recommended.is_pinned OR candidate_recommended.is_following_creator THEN 0
                    WHEN candidate_recommended.viewer_short_view_completion_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_short_rewatch_loop_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_creator_unlock_conversion_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_creator_main_click_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_creator_profile_click_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_creator_view_completion_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_creator_rewatch_loop_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_main_unlock_conversion_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_main_main_click_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_main_view_completion_count > 0 THEN 0
                    WHEN candidate_recommended.viewer_main_view_rewatch_loop_count > 0 THEN 0
                    ELSE ranking_weights.cold_candidate_bonus
                END
            )
        ) AS base_rank_score
    FROM candidate_recommended
    CROSS JOIN ranking_weights
    CROSS JOIN ranking_context
),
diversified_recommended AS (
    SELECT
        scored_recommended.id, scored_recommended.creator_user_id, scored_recommended.canonical_main_id, scored_recommended.media_asset_id, scored_recommended.caption, scored_recommended.published_at, scored_recommended.short_duration_ms, scored_recommended.display_name, scored_recommended.handle, scored_recommended.avatar_url, scored_recommended.bio, scored_recommended.main_price_minor, scored_recommended.main_duration_ms, scored_recommended.is_pinned, scored_recommended.is_unlocked, scored_recommended.is_owner, scored_recommended.is_following_creator, scored_recommended.viewer_short_view_completion_count, scored_recommended.viewer_short_rewatch_loop_count, scored_recommended.viewer_creator_unlock_conversion_count, scored_recommended.viewer_creator_main_click_count, scored_recommended.viewer_creator_profile_click_count, scored_recommended.viewer_creator_view_completion_count, scored_recommended.viewer_creator_rewatch_loop_count, scored_recommended.viewer_main_unlock_conversion_count, scored_recommended.viewer_main_main_click_count, scored_recommended.viewer_main_view_completion_count, scored_recommended.viewer_main_view_rewatch_loop_count, scored_recommended.short_global_impression_count, scored_recommended.short_global_unlock_conversion_count, scored_recommended.short_global_main_click_count, scored_recommended.short_global_view_completion_count, scored_recommended.short_global_view_rewatch_loop_count, scored_recommended.base_rank_score,
        ROW_NUMBER() OVER (
            PARTITION BY scored_recommended.creator_user_id
            ORDER BY scored_recommended.base_rank_score DESC, scored_recommended.published_at DESC, scored_recommended.id DESC
        ) AS creator_rank_position,
        ROW_NUMBER() OVER (
            PARTITION BY scored_recommended.canonical_main_id
            ORDER BY scored_recommended.base_rank_score DESC, scored_recommended.published_at DESC, scored_recommended.id DESC
        ) AS main_rank_position
    FROM scored_recommended
),
ordered_recommended AS (
    SELECT
        diversified_recommended.id,
        diversified_recommended.creator_user_id,
        diversified_recommended.canonical_main_id,
        diversified_recommended.media_asset_id,
        diversified_recommended.caption,
        diversified_recommended.published_at,
        diversified_recommended.short_duration_ms,
        diversified_recommended.display_name,
        diversified_recommended.handle,
        diversified_recommended.avatar_url,
        diversified_recommended.bio,
        diversified_recommended.main_price_minor,
        diversified_recommended.main_duration_ms,
        diversified_recommended.is_pinned,
        diversified_recommended.is_unlocked,
        diversified_recommended.is_owner,
        diversified_recommended.is_following_creator,
        (
            diversified_recommended.base_rank_score
            - ((diversified_recommended.creator_rank_position - 1) * ranking_weights.same_creator_penalty)
            - ((diversified_recommended.main_rank_position - 1) * ranking_weights.same_main_penalty)
        )::bigint AS rank_score
    FROM diversified_recommended
    CROSS JOIN ranking_weights
)
SELECT
    ordered_recommended.id
FROM ordered_recommended
ORDER BY ordered_recommended.rank_score DESC, ordered_recommended.published_at DESC, ordered_recommended.id DESC
`

type ListRecommendedPublicFeedShortIDsParams struct {
	RankingReferenceAt pgtype.Timestamptz
	LimitCount         int32
	ViewerUserID       pgtype.UUID
}

func (q *Queries) ListRecommendedPublicFeedShortIDs(ctx context.Context, arg ListRecommendedPublicFeedShortIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRecommendedPublicFeedShortIDs, arg.RankingReferenceAt, arg.LimitCount, arg.ViewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
