// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: purchase_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireMainPurchaseLock = `-- name: AcquireMainPurchaseLock :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1, 0),
    hashtextextended($2, 0)
)
`

type AcquireMainPurchaseLockParams struct {
	UserKey string
	MainKey string
}

func (q *Queries) AcquireMainPurchaseLock(ctx context.Context, arg AcquireMainPurchaseLockParams) error {
	_, err := q.db.Exec(ctx, acquireMainPurchaseLock, arg.UserKey, arg.MainKey)
	return err
}

const createMainPurchaseAttempt = `-- name: CreateMainPurchaseAttempt :one
INSERT INTO app.main_purchase_attempts (
    user_id,
    main_id,
    from_short_id,
    provider,
    payment_method_mode,
    user_payment_method_id,
    provider_payment_token_ref,
    idempotency_key,
    status,
    requested_price_jpy,
    requested_currency_code,
    accepted_age,
    accepted_terms
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
`

type CreateMainPurchaseAttemptParams struct {
	UserID                  pgtype.UUID
	MainID                  pgtype.UUID
	FromShortID             pgtype.UUID
	Provider                string
	PaymentMethodMode       string
	UserPaymentMethodID     pgtype.UUID
	ProviderPaymentTokenRef string
	IdempotencyKey          string
	Status                  string
	RequestedPriceJpy       int64
	RequestedCurrencyCode   int32
	AcceptedAge             bool
	AcceptedTerms           bool
}

func (q *Queries) CreateMainPurchaseAttempt(ctx context.Context, arg CreateMainPurchaseAttemptParams) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, createMainPurchaseAttempt,
		arg.UserID,
		arg.MainID,
		arg.FromShortID,
		arg.Provider,
		arg.PaymentMethodMode,
		arg.UserPaymentMethodID,
		arg.ProviderPaymentTokenRef,
		arg.IdempotencyKey,
		arg.Status,
		arg.RequestedPriceJpy,
		arg.RequestedCurrencyCode,
		arg.AcceptedAge,
		arg.AcceptedTerms,
	)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdate = `-- name: GetLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE user_id = $1
    AND main_id = $2
    AND status IN ('processing', 'pending')
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type GetLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdateParams struct {
	UserID pgtype.UUID
	MainID pgtype.UUID
}

func (q *Queries) GetLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdate(ctx context.Context, arg GetLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdateParams) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestInflightMainPurchaseAttemptByUserIDAndMainIDForUpdate, arg.UserID, arg.MainID)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdate = `-- name: GetLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE user_id = $1
    AND main_id = $2
    AND status = 'succeeded'
ORDER BY provider_processed_at DESC NULLS LAST, created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type GetLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdateParams struct {
	UserID pgtype.UUID
	MainID pgtype.UUID
}

func (q *Queries) GetLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdate(ctx context.Context, arg GetLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdateParams) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestSucceededMainPurchaseAttemptByUserIDAndMainIDForUpdate, arg.UserID, arg.MainID)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainPurchaseAttemptByID = `-- name: GetMainPurchaseAttemptByID :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMainPurchaseAttemptByID(ctx context.Context, id pgtype.UUID) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getMainPurchaseAttemptByID, id)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainPurchaseAttemptByIDForUpdate = `-- name: GetMainPurchaseAttemptByIDForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetMainPurchaseAttemptByIDForUpdate(ctx context.Context, id pgtype.UUID) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getMainPurchaseAttemptByIDForUpdate, id)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainPurchaseAttemptByIdempotencyKeyForUpdate = `-- name: GetMainPurchaseAttemptByIdempotencyKeyForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE idempotency_key = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetMainPurchaseAttemptByIdempotencyKeyForUpdate(ctx context.Context, idempotencyKey string) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getMainPurchaseAttemptByIdempotencyKeyForUpdate, idempotencyKey)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainPurchaseAttemptByProviderPurchaseRefForUpdate = `-- name: GetMainPurchaseAttemptByProviderPurchaseRefForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE provider_purchase_ref = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetMainPurchaseAttemptByProviderPurchaseRefForUpdate(ctx context.Context, providerPurchaseRef pgtype.Text) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getMainPurchaseAttemptByProviderPurchaseRefForUpdate, providerPurchaseRef)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMainPurchaseAttemptByProviderTransactionRefForUpdate = `-- name: GetMainPurchaseAttemptByProviderTransactionRefForUpdate :one
SELECT id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
FROM app.main_purchase_attempts
WHERE provider_transaction_ref = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetMainPurchaseAttemptByProviderTransactionRefForUpdate(ctx context.Context, providerTransactionRef pgtype.Text) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, getMainPurchaseAttemptByProviderTransactionRefForUpdate, providerTransactionRef)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMainPurchaseAttemptOutcome = `-- name: UpdateMainPurchaseAttemptOutcome :one
UPDATE app.main_purchase_attempts
SET status = $1,
    failure_reason = $2,
    pending_reason = $3,
    provider_payment_token_ref = COALESCE($4, provider_payment_token_ref),
    provider_purchase_ref = COALESCE($5, provider_purchase_ref),
    provider_transaction_ref = COALESCE($6, provider_transaction_ref),
    provider_session_ref = COALESCE($7, provider_session_ref),
    provider_payment_unique_ref = COALESCE($8, provider_payment_unique_ref),
    provider_decline_code = COALESCE($9, provider_decline_code),
    provider_decline_text = COALESCE($10, provider_decline_text),
    provider_processed_at = COALESCE($11::timestamptz, provider_processed_at),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $12
RETURNING id, user_id, main_id, from_short_id, provider, payment_method_mode, user_payment_method_id, provider_payment_token_ref, idempotency_key, status, failure_reason, pending_reason, provider_purchase_ref, provider_transaction_ref, provider_session_ref, provider_payment_unique_ref, provider_decline_code, provider_decline_text, requested_price_jpy, requested_currency_code, accepted_age, accepted_terms, provider_processed_at, created_at, updated_at
`

type UpdateMainPurchaseAttemptOutcomeParams struct {
	Status                   string
	FailureReason            pgtype.Text
	PendingReason            pgtype.Text
	ProviderPaymentTokenRef  pgtype.Text
	ProviderPurchaseRef      pgtype.Text
	ProviderTransactionRef   pgtype.Text
	ProviderSessionRef       pgtype.Text
	ProviderPaymentUniqueRef pgtype.Text
	ProviderDeclineCode      pgtype.Int4
	ProviderDeclineText      pgtype.Text
	ProviderProcessedAt      pgtype.Timestamptz
	ID                       pgtype.UUID
}

func (q *Queries) UpdateMainPurchaseAttemptOutcome(ctx context.Context, arg UpdateMainPurchaseAttemptOutcomeParams) (AppMainPurchaseAttempt, error) {
	row := q.db.QueryRow(ctx, updateMainPurchaseAttemptOutcome,
		arg.Status,
		arg.FailureReason,
		arg.PendingReason,
		arg.ProviderPaymentTokenRef,
		arg.ProviderPurchaseRef,
		arg.ProviderTransactionRef,
		arg.ProviderSessionRef,
		arg.ProviderPaymentUniqueRef,
		arg.ProviderDeclineCode,
		arg.ProviderDeclineText,
		arg.ProviderProcessedAt,
		arg.ID,
	)
	var i AppMainPurchaseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MainID,
		&i.FromShortID,
		&i.Provider,
		&i.PaymentMethodMode,
		&i.UserPaymentMethodID,
		&i.ProviderPaymentTokenRef,
		&i.IdempotencyKey,
		&i.Status,
		&i.FailureReason,
		&i.PendingReason,
		&i.ProviderPurchaseRef,
		&i.ProviderTransactionRef,
		&i.ProviderSessionRef,
		&i.ProviderPaymentUniqueRef,
		&i.ProviderDeclineCode,
		&i.ProviderDeclineText,
		&i.RequestedPriceJpy,
		&i.RequestedCurrencyCode,
		&i.AcceptedAge,
		&i.AcceptedTerms,
		&i.ProviderProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
