// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recommendation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecommendationEventByViewerAndIdempotencyKey = `-- name: GetRecommendationEventByViewerAndIdempotencyKey :one
SELECT
    id,
    viewer_user_id,
    event_kind,
    creator_user_id,
    canonical_main_id,
    short_id,
    occurred_at,
    idempotency_key,
    created_at,
    updated_at
FROM app.recommendation_events
WHERE viewer_user_id = $1
    AND idempotency_key = $2
LIMIT 1
`

type GetRecommendationEventByViewerAndIdempotencyKeyParams struct {
	ViewerUserID   pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) GetRecommendationEventByViewerAndIdempotencyKey(ctx context.Context, arg GetRecommendationEventByViewerAndIdempotencyKeyParams) (AppRecommendationEvent, error) {
	row := q.db.QueryRow(ctx, getRecommendationEventByViewerAndIdempotencyKey, arg.ViewerUserID, arg.IdempotencyKey)
	var i AppRecommendationEvent
	err := row.Scan(
		&i.ID,
		&i.ViewerUserID,
		&i.EventKind,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.ShortID,
		&i.OccurredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecommendationEvent = `-- name: InsertRecommendationEvent :one
INSERT INTO app.recommendation_events (
    viewer_user_id,
    event_kind,
    creator_user_id,
    canonical_main_id,
    short_id,
    occurred_at,
    idempotency_key
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (viewer_user_id, idempotency_key) DO NOTHING
RETURNING
    id,
    viewer_user_id,
    event_kind,
    creator_user_id,
    canonical_main_id,
    short_id,
    occurred_at,
    idempotency_key,
    created_at,
    updated_at
`

type InsertRecommendationEventParams struct {
	ViewerUserID    pgtype.UUID
	EventKind       string
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	ShortID         pgtype.UUID
	OccurredAt      pgtype.Timestamptz
	IdempotencyKey  string
}

func (q *Queries) InsertRecommendationEvent(ctx context.Context, arg InsertRecommendationEventParams) (AppRecommendationEvent, error) {
	row := q.db.QueryRow(ctx, insertRecommendationEvent,
		arg.ViewerUserID,
		arg.EventKind,
		arg.CreatorUserID,
		arg.CanonicalMainID,
		arg.ShortID,
		arg.OccurredAt,
		arg.IdempotencyKey,
	)
	var i AppRecommendationEvent
	err := row.Scan(
		&i.ID,
		&i.ViewerUserID,
		&i.EventKind,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.ShortID,
		&i.OccurredAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecommendationFollowedCreatorIDsByViewerAndCreatorIDs = `-- name: ListRecommendationFollowedCreatorIDsByViewerAndCreatorIDs :many
SELECT creator_user_id
FROM app.creator_follows
WHERE user_id = $1
    AND creator_user_id = ANY($2::uuid[])
ORDER BY creator_user_id ASC
`

type ListRecommendationFollowedCreatorIDsByViewerAndCreatorIDsParams struct {
	ViewerUserID   pgtype.UUID
	CreatorUserIds []pgtype.UUID
}

func (q *Queries) ListRecommendationFollowedCreatorIDsByViewerAndCreatorIDs(ctx context.Context, arg ListRecommendationFollowedCreatorIDsByViewerAndCreatorIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRecommendationFollowedCreatorIDsByViewerAndCreatorIDs, arg.ViewerUserID, arg.CreatorUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var creator_user_id pgtype.UUID
		if err := rows.Scan(&creator_user_id); err != nil {
			return nil, err
		}
		items = append(items, creator_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationPinnedShortIDsByViewerAndShortIDs = `-- name: ListRecommendationPinnedShortIDsByViewerAndShortIDs :many
SELECT short_id
FROM app.pinned_shorts
WHERE user_id = $1
    AND short_id = ANY($2::uuid[])
ORDER BY short_id ASC
`

type ListRecommendationPinnedShortIDsByViewerAndShortIDsParams struct {
	ViewerUserID pgtype.UUID
	ShortIds     []pgtype.UUID
}

func (q *Queries) ListRecommendationPinnedShortIDsByViewerAndShortIDs(ctx context.Context, arg ListRecommendationPinnedShortIDsByViewerAndShortIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRecommendationPinnedShortIDsByViewerAndShortIDs, arg.ViewerUserID, arg.ShortIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var short_id pgtype.UUID
		if err := rows.Scan(&short_id); err != nil {
			return nil, err
		}
		items = append(items, short_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationShortGlobalFeaturesByShortIDs = `-- name: ListRecommendationShortGlobalFeaturesByShortIDs :many
SELECT short_id, creator_user_id, canonical_main_id, impression_count, last_impression_at, view_start_count, last_view_start_at, view_completion_count, last_view_completion_at, rewatch_loop_count, last_rewatch_loop_at, main_click_count, last_main_click_at, unlock_conversion_count, last_unlock_conversion_at, created_at, updated_at
FROM app.recommendation_short_global_features
WHERE short_id = ANY($1::uuid[])
ORDER BY short_id ASC
`

func (q *Queries) ListRecommendationShortGlobalFeaturesByShortIDs(ctx context.Context, shortIds []pgtype.UUID) ([]AppRecommendationShortGlobalFeature, error) {
	rows, err := q.db.Query(ctx, listRecommendationShortGlobalFeaturesByShortIDs, shortIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRecommendationShortGlobalFeature
	for rows.Next() {
		var i AppRecommendationShortGlobalFeature
		if err := rows.Scan(
			&i.ShortID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.ImpressionCount,
			&i.LastImpressionAt,
			&i.ViewStartCount,
			&i.LastViewStartAt,
			&i.ViewCompletionCount,
			&i.LastViewCompletionAt,
			&i.RewatchLoopCount,
			&i.LastRewatchLoopAt,
			&i.MainClickCount,
			&i.LastMainClickAt,
			&i.UnlockConversionCount,
			&i.LastUnlockConversionAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationUnlockedMainIDsByViewerAndMainIDs = `-- name: ListRecommendationUnlockedMainIDsByViewerAndMainIDs :many
SELECT main_id
FROM app.main_unlocks
WHERE user_id = $1
    AND main_id = ANY($2::uuid[])
ORDER BY main_id ASC
`

type ListRecommendationUnlockedMainIDsByViewerAndMainIDsParams struct {
	ViewerUserID     pgtype.UUID
	CanonicalMainIds []pgtype.UUID
}

func (q *Queries) ListRecommendationUnlockedMainIDsByViewerAndMainIDs(ctx context.Context, arg ListRecommendationUnlockedMainIDsByViewerAndMainIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRecommendationUnlockedMainIDsByViewerAndMainIDs, arg.ViewerUserID, arg.CanonicalMainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var main_id pgtype.UUID
		if err := rows.Scan(&main_id); err != nil {
			return nil, err
		}
		items = append(items, main_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationViewerCreatorFeaturesByViewerAndCreatorIDs = `-- name: ListRecommendationViewerCreatorFeaturesByViewerAndCreatorIDs :many
SELECT viewer_user_id, creator_user_id, impression_count, last_impression_at, view_start_count, last_view_start_at, view_completion_count, last_view_completion_at, rewatch_loop_count, last_rewatch_loop_at, profile_click_count, last_profile_click_at, main_click_count, last_main_click_at, unlock_conversion_count, last_unlock_conversion_at, created_at, updated_at
FROM app.recommendation_viewer_creator_features
WHERE viewer_user_id = $1
    AND creator_user_id = ANY($2::uuid[])
ORDER BY creator_user_id ASC
`

type ListRecommendationViewerCreatorFeaturesByViewerAndCreatorIDsParams struct {
	ViewerUserID   pgtype.UUID
	CreatorUserIds []pgtype.UUID
}

func (q *Queries) ListRecommendationViewerCreatorFeaturesByViewerAndCreatorIDs(ctx context.Context, arg ListRecommendationViewerCreatorFeaturesByViewerAndCreatorIDsParams) ([]AppRecommendationViewerCreatorFeature, error) {
	rows, err := q.db.Query(ctx, listRecommendationViewerCreatorFeaturesByViewerAndCreatorIDs, arg.ViewerUserID, arg.CreatorUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRecommendationViewerCreatorFeature
	for rows.Next() {
		var i AppRecommendationViewerCreatorFeature
		if err := rows.Scan(
			&i.ViewerUserID,
			&i.CreatorUserID,
			&i.ImpressionCount,
			&i.LastImpressionAt,
			&i.ViewStartCount,
			&i.LastViewStartAt,
			&i.ViewCompletionCount,
			&i.LastViewCompletionAt,
			&i.RewatchLoopCount,
			&i.LastRewatchLoopAt,
			&i.ProfileClickCount,
			&i.LastProfileClickAt,
			&i.MainClickCount,
			&i.LastMainClickAt,
			&i.UnlockConversionCount,
			&i.LastUnlockConversionAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationViewerMainFeaturesByViewerAndMainIDs = `-- name: ListRecommendationViewerMainFeaturesByViewerAndMainIDs :many
SELECT viewer_user_id, canonical_main_id, creator_user_id, impression_count, last_impression_at, view_start_count, last_view_start_at, view_completion_count, last_view_completion_at, rewatch_loop_count, last_rewatch_loop_at, main_click_count, last_main_click_at, unlock_conversion_count, last_unlock_conversion_at, created_at, updated_at
FROM app.recommendation_viewer_main_features
WHERE viewer_user_id = $1
    AND canonical_main_id = ANY($2::uuid[])
ORDER BY canonical_main_id ASC
`

type ListRecommendationViewerMainFeaturesByViewerAndMainIDsParams struct {
	ViewerUserID     pgtype.UUID
	CanonicalMainIds []pgtype.UUID
}

func (q *Queries) ListRecommendationViewerMainFeaturesByViewerAndMainIDs(ctx context.Context, arg ListRecommendationViewerMainFeaturesByViewerAndMainIDsParams) ([]AppRecommendationViewerMainFeature, error) {
	rows, err := q.db.Query(ctx, listRecommendationViewerMainFeaturesByViewerAndMainIDs, arg.ViewerUserID, arg.CanonicalMainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRecommendationViewerMainFeature
	for rows.Next() {
		var i AppRecommendationViewerMainFeature
		if err := rows.Scan(
			&i.ViewerUserID,
			&i.CanonicalMainID,
			&i.CreatorUserID,
			&i.ImpressionCount,
			&i.LastImpressionAt,
			&i.ViewStartCount,
			&i.LastViewStartAt,
			&i.ViewCompletionCount,
			&i.LastViewCompletionAt,
			&i.RewatchLoopCount,
			&i.LastRewatchLoopAt,
			&i.MainClickCount,
			&i.LastMainClickAt,
			&i.UnlockConversionCount,
			&i.LastUnlockConversionAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationViewerShortFeaturesByViewerAndShortIDs = `-- name: ListRecommendationViewerShortFeaturesByViewerAndShortIDs :many
SELECT viewer_user_id, short_id, creator_user_id, canonical_main_id, impression_count, last_impression_at, view_start_count, last_view_start_at, view_completion_count, last_view_completion_at, rewatch_loop_count, last_rewatch_loop_at, main_click_count, last_main_click_at, unlock_conversion_count, last_unlock_conversion_at, created_at, updated_at
FROM app.recommendation_viewer_short_features
WHERE viewer_user_id = $1
    AND short_id = ANY($2::uuid[])
ORDER BY short_id ASC
`

type ListRecommendationViewerShortFeaturesByViewerAndShortIDsParams struct {
	ViewerUserID pgtype.UUID
	ShortIds     []pgtype.UUID
}

func (q *Queries) ListRecommendationViewerShortFeaturesByViewerAndShortIDs(ctx context.Context, arg ListRecommendationViewerShortFeaturesByViewerAndShortIDsParams) ([]AppRecommendationViewerShortFeature, error) {
	rows, err := q.db.Query(ctx, listRecommendationViewerShortFeaturesByViewerAndShortIDs, arg.ViewerUserID, arg.ShortIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRecommendationViewerShortFeature
	for rows.Next() {
		var i AppRecommendationViewerShortFeature
		if err := rows.Scan(
			&i.ViewerUserID,
			&i.ShortID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.ImpressionCount,
			&i.LastImpressionAt,
			&i.ViewStartCount,
			&i.LastViewStartAt,
			&i.ViewCompletionCount,
			&i.LastViewCompletionAt,
			&i.RewatchLoopCount,
			&i.LastRewatchLoopAt,
			&i.MainClickCount,
			&i.LastMainClickAt,
			&i.UnlockConversionCount,
			&i.LastUnlockConversionAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecommendationShortGlobalFeatures = `-- name: UpsertRecommendationShortGlobalFeatures :execrows
INSERT INTO app.recommendation_short_global_features (
    short_id,
    creator_user_id,
    canonical_main_id,
    impression_count,
    last_impression_at,
    view_start_count,
    last_view_start_at,
    view_completion_count,
    last_view_completion_at,
    rewatch_loop_count,
    last_rewatch_loop_at,
    main_click_count,
    last_main_click_at,
    unlock_conversion_count,
    last_unlock_conversion_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (short_id) DO UPDATE
SET
    impression_count = app.recommendation_short_global_features.impression_count + EXCLUDED.impression_count,
    last_impression_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_impression_at, EXCLUDED.last_impression_at),
        app.recommendation_short_global_features.last_impression_at,
        EXCLUDED.last_impression_at
    ),
    view_start_count = app.recommendation_short_global_features.view_start_count + EXCLUDED.view_start_count,
    last_view_start_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_view_start_at, EXCLUDED.last_view_start_at),
        app.recommendation_short_global_features.last_view_start_at,
        EXCLUDED.last_view_start_at
    ),
    view_completion_count = app.recommendation_short_global_features.view_completion_count + EXCLUDED.view_completion_count,
    last_view_completion_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_view_completion_at, EXCLUDED.last_view_completion_at),
        app.recommendation_short_global_features.last_view_completion_at,
        EXCLUDED.last_view_completion_at
    ),
    rewatch_loop_count = app.recommendation_short_global_features.rewatch_loop_count + EXCLUDED.rewatch_loop_count,
    last_rewatch_loop_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_rewatch_loop_at, EXCLUDED.last_rewatch_loop_at),
        app.recommendation_short_global_features.last_rewatch_loop_at,
        EXCLUDED.last_rewatch_loop_at
    ),
    main_click_count = app.recommendation_short_global_features.main_click_count + EXCLUDED.main_click_count,
    last_main_click_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_main_click_at, EXCLUDED.last_main_click_at),
        app.recommendation_short_global_features.last_main_click_at,
        EXCLUDED.last_main_click_at
    ),
    unlock_conversion_count = app.recommendation_short_global_features.unlock_conversion_count + EXCLUDED.unlock_conversion_count,
    last_unlock_conversion_at = COALESCE(
        GREATEST(app.recommendation_short_global_features.last_unlock_conversion_at, EXCLUDED.last_unlock_conversion_at),
        app.recommendation_short_global_features.last_unlock_conversion_at,
        EXCLUDED.last_unlock_conversion_at
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE app.recommendation_short_global_features.creator_user_id = EXCLUDED.creator_user_id
    AND app.recommendation_short_global_features.canonical_main_id = EXCLUDED.canonical_main_id
`

type UpsertRecommendationShortGlobalFeaturesParams struct {
	ShortID                pgtype.UUID
	CreatorUserID          pgtype.UUID
	CanonicalMainID        pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
}

func (q *Queries) UpsertRecommendationShortGlobalFeatures(ctx context.Context, arg UpsertRecommendationShortGlobalFeaturesParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRecommendationShortGlobalFeatures,
		arg.ShortID,
		arg.CreatorUserID,
		arg.CanonicalMainID,
		arg.ImpressionCount,
		arg.LastImpressionAt,
		arg.ViewStartCount,
		arg.LastViewStartAt,
		arg.ViewCompletionCount,
		arg.LastViewCompletionAt,
		arg.RewatchLoopCount,
		arg.LastRewatchLoopAt,
		arg.MainClickCount,
		arg.LastMainClickAt,
		arg.UnlockConversionCount,
		arg.LastUnlockConversionAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRecommendationViewerCreatorFeatures = `-- name: UpsertRecommendationViewerCreatorFeatures :exec
INSERT INTO app.recommendation_viewer_creator_features (
    viewer_user_id,
    creator_user_id,
    impression_count,
    last_impression_at,
    view_start_count,
    last_view_start_at,
    view_completion_count,
    last_view_completion_at,
    rewatch_loop_count,
    last_rewatch_loop_at,
    profile_click_count,
    last_profile_click_at,
    main_click_count,
    last_main_click_at,
    unlock_conversion_count,
    last_unlock_conversion_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
ON CONFLICT (viewer_user_id, creator_user_id) DO UPDATE
SET
    impression_count = app.recommendation_viewer_creator_features.impression_count + EXCLUDED.impression_count,
    last_impression_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_impression_at, EXCLUDED.last_impression_at),
        app.recommendation_viewer_creator_features.last_impression_at,
        EXCLUDED.last_impression_at
    ),
    view_start_count = app.recommendation_viewer_creator_features.view_start_count + EXCLUDED.view_start_count,
    last_view_start_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_view_start_at, EXCLUDED.last_view_start_at),
        app.recommendation_viewer_creator_features.last_view_start_at,
        EXCLUDED.last_view_start_at
    ),
    view_completion_count = app.recommendation_viewer_creator_features.view_completion_count + EXCLUDED.view_completion_count,
    last_view_completion_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_view_completion_at, EXCLUDED.last_view_completion_at),
        app.recommendation_viewer_creator_features.last_view_completion_at,
        EXCLUDED.last_view_completion_at
    ),
    rewatch_loop_count = app.recommendation_viewer_creator_features.rewatch_loop_count + EXCLUDED.rewatch_loop_count,
    last_rewatch_loop_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_rewatch_loop_at, EXCLUDED.last_rewatch_loop_at),
        app.recommendation_viewer_creator_features.last_rewatch_loop_at,
        EXCLUDED.last_rewatch_loop_at
    ),
    profile_click_count = app.recommendation_viewer_creator_features.profile_click_count + EXCLUDED.profile_click_count,
    last_profile_click_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_profile_click_at, EXCLUDED.last_profile_click_at),
        app.recommendation_viewer_creator_features.last_profile_click_at,
        EXCLUDED.last_profile_click_at
    ),
    main_click_count = app.recommendation_viewer_creator_features.main_click_count + EXCLUDED.main_click_count,
    last_main_click_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_main_click_at, EXCLUDED.last_main_click_at),
        app.recommendation_viewer_creator_features.last_main_click_at,
        EXCLUDED.last_main_click_at
    ),
    unlock_conversion_count = app.recommendation_viewer_creator_features.unlock_conversion_count + EXCLUDED.unlock_conversion_count,
    last_unlock_conversion_at = COALESCE(
        GREATEST(app.recommendation_viewer_creator_features.last_unlock_conversion_at, EXCLUDED.last_unlock_conversion_at),
        app.recommendation_viewer_creator_features.last_unlock_conversion_at,
        EXCLUDED.last_unlock_conversion_at
    ),
    updated_at = CURRENT_TIMESTAMP
`

type UpsertRecommendationViewerCreatorFeaturesParams struct {
	ViewerUserID           pgtype.UUID
	CreatorUserID          pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	ProfileClickCount      int64
	LastProfileClickAt     pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
}

func (q *Queries) UpsertRecommendationViewerCreatorFeatures(ctx context.Context, arg UpsertRecommendationViewerCreatorFeaturesParams) error {
	_, err := q.db.Exec(ctx, upsertRecommendationViewerCreatorFeatures,
		arg.ViewerUserID,
		arg.CreatorUserID,
		arg.ImpressionCount,
		arg.LastImpressionAt,
		arg.ViewStartCount,
		arg.LastViewStartAt,
		arg.ViewCompletionCount,
		arg.LastViewCompletionAt,
		arg.RewatchLoopCount,
		arg.LastRewatchLoopAt,
		arg.ProfileClickCount,
		arg.LastProfileClickAt,
		arg.MainClickCount,
		arg.LastMainClickAt,
		arg.UnlockConversionCount,
		arg.LastUnlockConversionAt,
	)
	return err
}

const upsertRecommendationViewerMainFeatures = `-- name: UpsertRecommendationViewerMainFeatures :execrows
INSERT INTO app.recommendation_viewer_main_features (
    viewer_user_id,
    canonical_main_id,
    creator_user_id,
    impression_count,
    last_impression_at,
    view_start_count,
    last_view_start_at,
    view_completion_count,
    last_view_completion_at,
    rewatch_loop_count,
    last_rewatch_loop_at,
    main_click_count,
    last_main_click_at,
    unlock_conversion_count,
    last_unlock_conversion_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (viewer_user_id, canonical_main_id) DO UPDATE
SET
    impression_count = app.recommendation_viewer_main_features.impression_count + EXCLUDED.impression_count,
    last_impression_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_impression_at, EXCLUDED.last_impression_at),
        app.recommendation_viewer_main_features.last_impression_at,
        EXCLUDED.last_impression_at
    ),
    view_start_count = app.recommendation_viewer_main_features.view_start_count + EXCLUDED.view_start_count,
    last_view_start_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_view_start_at, EXCLUDED.last_view_start_at),
        app.recommendation_viewer_main_features.last_view_start_at,
        EXCLUDED.last_view_start_at
    ),
    view_completion_count = app.recommendation_viewer_main_features.view_completion_count + EXCLUDED.view_completion_count,
    last_view_completion_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_view_completion_at, EXCLUDED.last_view_completion_at),
        app.recommendation_viewer_main_features.last_view_completion_at,
        EXCLUDED.last_view_completion_at
    ),
    rewatch_loop_count = app.recommendation_viewer_main_features.rewatch_loop_count + EXCLUDED.rewatch_loop_count,
    last_rewatch_loop_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_rewatch_loop_at, EXCLUDED.last_rewatch_loop_at),
        app.recommendation_viewer_main_features.last_rewatch_loop_at,
        EXCLUDED.last_rewatch_loop_at
    ),
    main_click_count = app.recommendation_viewer_main_features.main_click_count + EXCLUDED.main_click_count,
    last_main_click_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_main_click_at, EXCLUDED.last_main_click_at),
        app.recommendation_viewer_main_features.last_main_click_at,
        EXCLUDED.last_main_click_at
    ),
    unlock_conversion_count = app.recommendation_viewer_main_features.unlock_conversion_count + EXCLUDED.unlock_conversion_count,
    last_unlock_conversion_at = COALESCE(
        GREATEST(app.recommendation_viewer_main_features.last_unlock_conversion_at, EXCLUDED.last_unlock_conversion_at),
        app.recommendation_viewer_main_features.last_unlock_conversion_at,
        EXCLUDED.last_unlock_conversion_at
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE app.recommendation_viewer_main_features.creator_user_id = EXCLUDED.creator_user_id
`

type UpsertRecommendationViewerMainFeaturesParams struct {
	ViewerUserID           pgtype.UUID
	CanonicalMainID        pgtype.UUID
	CreatorUserID          pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
}

func (q *Queries) UpsertRecommendationViewerMainFeatures(ctx context.Context, arg UpsertRecommendationViewerMainFeaturesParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRecommendationViewerMainFeatures,
		arg.ViewerUserID,
		arg.CanonicalMainID,
		arg.CreatorUserID,
		arg.ImpressionCount,
		arg.LastImpressionAt,
		arg.ViewStartCount,
		arg.LastViewStartAt,
		arg.ViewCompletionCount,
		arg.LastViewCompletionAt,
		arg.RewatchLoopCount,
		arg.LastRewatchLoopAt,
		arg.MainClickCount,
		arg.LastMainClickAt,
		arg.UnlockConversionCount,
		arg.LastUnlockConversionAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRecommendationViewerShortFeatures = `-- name: UpsertRecommendationViewerShortFeatures :execrows
INSERT INTO app.recommendation_viewer_short_features (
    viewer_user_id,
    short_id,
    creator_user_id,
    canonical_main_id,
    impression_count,
    last_impression_at,
    view_start_count,
    last_view_start_at,
    view_completion_count,
    last_view_completion_at,
    rewatch_loop_count,
    last_rewatch_loop_at,
    main_click_count,
    last_main_click_at,
    unlock_conversion_count,
    last_unlock_conversion_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
ON CONFLICT (viewer_user_id, short_id) DO UPDATE
SET
    impression_count = app.recommendation_viewer_short_features.impression_count + EXCLUDED.impression_count,
    last_impression_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_impression_at, EXCLUDED.last_impression_at),
        app.recommendation_viewer_short_features.last_impression_at,
        EXCLUDED.last_impression_at
    ),
    view_start_count = app.recommendation_viewer_short_features.view_start_count + EXCLUDED.view_start_count,
    last_view_start_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_view_start_at, EXCLUDED.last_view_start_at),
        app.recommendation_viewer_short_features.last_view_start_at,
        EXCLUDED.last_view_start_at
    ),
    view_completion_count = app.recommendation_viewer_short_features.view_completion_count + EXCLUDED.view_completion_count,
    last_view_completion_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_view_completion_at, EXCLUDED.last_view_completion_at),
        app.recommendation_viewer_short_features.last_view_completion_at,
        EXCLUDED.last_view_completion_at
    ),
    rewatch_loop_count = app.recommendation_viewer_short_features.rewatch_loop_count + EXCLUDED.rewatch_loop_count,
    last_rewatch_loop_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_rewatch_loop_at, EXCLUDED.last_rewatch_loop_at),
        app.recommendation_viewer_short_features.last_rewatch_loop_at,
        EXCLUDED.last_rewatch_loop_at
    ),
    main_click_count = app.recommendation_viewer_short_features.main_click_count + EXCLUDED.main_click_count,
    last_main_click_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_main_click_at, EXCLUDED.last_main_click_at),
        app.recommendation_viewer_short_features.last_main_click_at,
        EXCLUDED.last_main_click_at
    ),
    unlock_conversion_count = app.recommendation_viewer_short_features.unlock_conversion_count + EXCLUDED.unlock_conversion_count,
    last_unlock_conversion_at = COALESCE(
        GREATEST(app.recommendation_viewer_short_features.last_unlock_conversion_at, EXCLUDED.last_unlock_conversion_at),
        app.recommendation_viewer_short_features.last_unlock_conversion_at,
        EXCLUDED.last_unlock_conversion_at
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE app.recommendation_viewer_short_features.creator_user_id = EXCLUDED.creator_user_id
    AND app.recommendation_viewer_short_features.canonical_main_id = EXCLUDED.canonical_main_id
`

type UpsertRecommendationViewerShortFeaturesParams struct {
	ViewerUserID           pgtype.UUID
	ShortID                pgtype.UUID
	CreatorUserID          pgtype.UUID
	CanonicalMainID        pgtype.UUID
	ImpressionCount        int64
	LastImpressionAt       pgtype.Timestamptz
	ViewStartCount         int64
	LastViewStartAt        pgtype.Timestamptz
	ViewCompletionCount    int64
	LastViewCompletionAt   pgtype.Timestamptz
	RewatchLoopCount       int64
	LastRewatchLoopAt      pgtype.Timestamptz
	MainClickCount         int64
	LastMainClickAt        pgtype.Timestamptz
	UnlockConversionCount  int64
	LastUnlockConversionAt pgtype.Timestamptz
}

func (q *Queries) UpsertRecommendationViewerShortFeatures(ctx context.Context, arg UpsertRecommendationViewerShortFeaturesParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRecommendationViewerShortFeatures,
		arg.ViewerUserID,
		arg.ShortID,
		arg.CreatorUserID,
		arg.CanonicalMainID,
		arg.ImpressionCount,
		arg.LastImpressionAt,
		arg.ViewStartCount,
		arg.LastViewStartAt,
		arg.ViewCompletionCount,
		arg.LastViewCompletionAt,
		arg.RewatchLoopCount,
		arg.LastRewatchLoopAt,
		arg.MainClickCount,
		arg.LastMainClickAt,
		arg.UnlockConversionCount,
		arg.LastUnlockConversionAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
