// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: short_comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShortComment = `-- name: CreateShortComment :one
WITH public_short AS (
    SELECT public_shorts.id
    FROM app.public_shorts
    WHERE public_shorts.id = $1
),
author_profile AS (
    SELECT
        user_id,
        display_name,
        handle,
        avatar_url
    FROM app.user_profiles
    WHERE user_id = $2
),
inserted AS (
    INSERT INTO app.short_comments (
        short_id,
        author_user_id,
        body
    )
    SELECT
        public_short.id,
        author_profile.user_id,
        $3
    FROM public_short
    CROSS JOIN author_profile
    RETURNING
        id,
        short_id,
        author_user_id,
        body,
        created_at
)
SELECT
    inserted.id,
    inserted.short_id,
    inserted.author_user_id,
    inserted.body,
    inserted.created_at,
    author_profile.display_name,
    author_profile.handle,
    author_profile.avatar_url
FROM inserted
JOIN author_profile
    ON author_profile.user_id = inserted.author_user_id
`

type CreateShortCommentParams struct {
	ShortID      pgtype.UUID
	AuthorUserID pgtype.UUID
	Body         string
}

type CreateShortCommentRow struct {
	ID           pgtype.UUID
	ShortID      pgtype.UUID
	AuthorUserID pgtype.UUID
	Body         string
	CreatedAt    pgtype.Timestamptz
	DisplayName  string
	Handle       string
	AvatarUrl    pgtype.Text
}

func (q *Queries) CreateShortComment(ctx context.Context, arg CreateShortCommentParams) (CreateShortCommentRow, error) {
	row := q.db.QueryRow(ctx, createShortComment, arg.ShortID, arg.AuthorUserID, arg.Body)
	var i CreateShortCommentRow
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.AuthorUserID,
		&i.Body,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
	)
	return i, err
}

const getPublicShortForComments = `-- name: GetPublicShortForComments :one
SELECT id
FROM app.public_shorts
WHERE public_shorts.id = $1
`

func (q *Queries) GetPublicShortForComments(ctx context.Context, shortID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPublicShortForComments, shortID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listShortCommentsAfterCursor = `-- name: ListShortCommentsAfterCursor :many
WITH public_short AS (
    SELECT public_shorts.id
    FROM app.public_shorts
    WHERE public_shorts.id = $1
),
comment_page AS (
    SELECT
        short_comment.id,
        short_comment.short_id,
        short_comment.author_user_id,
        short_comment.body,
        short_comment.created_at
    FROM app.short_comments AS short_comment
    WHERE short_comment.short_id = $1
        AND (short_comment.created_at, short_comment.id) < (
            $2::timestamptz,
            $3::uuid
        )
    ORDER BY short_comment.created_at DESC, short_comment.id DESC
    LIMIT $4
)
SELECT
    public_short.id AS public_short_id,
    comment_page.id,
    comment_page.short_id,
    comment_page.author_user_id,
    comment_page.body,
    comment_page.created_at,
    user_profile.display_name,
    user_profile.handle,
    user_profile.avatar_url
FROM public_short
LEFT JOIN comment_page
    ON TRUE
LEFT JOIN app.user_profiles AS user_profile
    ON user_profile.user_id = comment_page.author_user_id
ORDER BY comment_page.created_at DESC NULLS LAST, comment_page.id DESC NULLS LAST
`

type ListShortCommentsAfterCursorParams struct {
	ShortID         pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorCommentID pgtype.UUID
	LimitCount      int32
}

type ListShortCommentsAfterCursorRow struct {
	PublicShortID pgtype.UUID
	ID            pgtype.UUID
	ShortID       pgtype.UUID
	AuthorUserID  pgtype.UUID
	Body          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	DisplayName   pgtype.Text
	Handle        pgtype.Text
	AvatarUrl     pgtype.Text
}

func (q *Queries) ListShortCommentsAfterCursor(ctx context.Context, arg ListShortCommentsAfterCursorParams) ([]ListShortCommentsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listShortCommentsAfterCursor,
		arg.ShortID,
		arg.CursorCreatedAt,
		arg.CursorCommentID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShortCommentsAfterCursorRow
	for rows.Next() {
		var i ListShortCommentsAfterCursorRow
		if err := rows.Scan(
			&i.PublicShortID,
			&i.ID,
			&i.ShortID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortCommentsFirstPage = `-- name: ListShortCommentsFirstPage :many
WITH public_short AS (
    SELECT public_shorts.id
    FROM app.public_shorts
    WHERE public_shorts.id = $1
),
comment_page AS (
    SELECT
        short_comment.id,
        short_comment.short_id,
        short_comment.author_user_id,
        short_comment.body,
        short_comment.created_at
    FROM app.short_comments AS short_comment
    WHERE short_comment.short_id = $1
    ORDER BY short_comment.created_at DESC, short_comment.id DESC
    LIMIT $2
)
SELECT
    public_short.id AS public_short_id,
    comment_page.id,
    comment_page.short_id,
    comment_page.author_user_id,
    comment_page.body,
    comment_page.created_at,
    user_profile.display_name,
    user_profile.handle,
    user_profile.avatar_url
FROM public_short
LEFT JOIN comment_page
    ON TRUE
LEFT JOIN app.user_profiles AS user_profile
    ON user_profile.user_id = comment_page.author_user_id
ORDER BY comment_page.created_at DESC NULLS LAST, comment_page.id DESC NULLS LAST
`

type ListShortCommentsFirstPageParams struct {
	ShortID    pgtype.UUID
	LimitCount int32
}

type ListShortCommentsFirstPageRow struct {
	PublicShortID pgtype.UUID
	ID            pgtype.UUID
	ShortID       pgtype.UUID
	AuthorUserID  pgtype.UUID
	Body          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	DisplayName   pgtype.Text
	Handle        pgtype.Text
	AvatarUrl     pgtype.Text
}

func (q *Queries) ListShortCommentsFirstPage(ctx context.Context, arg ListShortCommentsFirstPageParams) ([]ListShortCommentsFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listShortCommentsFirstPage, arg.ShortID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShortCommentsFirstPageRow
	for rows.Next() {
		var i ListShortCommentsFirstPageRow
		if err := rows.Scan(
			&i.PublicShortID,
			&i.ID,
			&i.ShortID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
