// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: short_main_links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCanonicalMainIDByShortID = `-- name: GetCanonicalMainIDByShortID :one
SELECT canonical_main_id
FROM app.shorts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCanonicalMainIDByShortID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCanonicalMainIDByShortID, id)
	var canonical_main_id pgtype.UUID
	err := row.Scan(&canonical_main_id)
	return canonical_main_id, err
}

const listShortsByCanonicalMainID = `-- name: ListShortsByCanonicalMainID :many
SELECT id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
FROM app.shorts
WHERE canonical_main_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListShortsByCanonicalMainID(ctx context.Context, canonicalMainID pgtype.UUID) ([]AppShort, error) {
	rows, err := q.db.Query(ctx, listShortsByCanonicalMainID, canonicalMainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppShort
	for rows.Next() {
		var i AppShort
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.ApprovedForPublishAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
