// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shorts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicShortsByCreatorUserID = `-- name: CountPublicShortsByCreatorUserID :one
SELECT COUNT(*)::bigint
FROM app.public_shorts
WHERE creator_user_id = $1
`

func (q *Queries) CountPublicShortsByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicShortsByCreatorUserID, creatorUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createShort = `-- name: CreateShort :one
INSERT INTO app.shorts (
    creator_user_id,
    canonical_main_id,
    media_asset_id,
    state,
    review_reason_code,
    post_report_state,
    approved_for_publish_at,
    published_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
`

type CreateShortParams struct {
	CreatorUserID        pgtype.UUID
	CanonicalMainID      pgtype.UUID
	MediaAssetID         pgtype.UUID
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	ApprovedForPublishAt pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
}

func (q *Queries) CreateShort(ctx context.Context, arg CreateShortParams) (AppShort, error) {
	row := q.db.QueryRow(ctx, createShort,
		arg.CreatorUserID,
		arg.CanonicalMainID,
		arg.MediaAssetID,
		arg.State,
		arg.ReviewReasonCode,
		arg.PostReportState,
		arg.ApprovedForPublishAt,
		arg.PublishedAt,
	)
	var i AppShort
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.ApprovedForPublishAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicShortByID = `-- name: GetPublicShortByID :one
SELECT id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
FROM app.public_shorts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPublicShortByID(ctx context.Context, id pgtype.UUID) (AppPublicShort, error) {
	row := q.db.QueryRow(ctx, getPublicShortByID, id)
	var i AppPublicShort
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.ApprovedForPublishAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortByID = `-- name: GetShortByID :one
SELECT id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
FROM app.shorts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetShortByID(ctx context.Context, id pgtype.UUID) (AppShort, error) {
	row := q.db.QueryRow(ctx, getShortByID, id)
	var i AppShort
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.ApprovedForPublishAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreatorProfileShortGridItems = `-- name: ListCreatorProfileShortGridItems :many
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.published_at,
    m.playback_url,
    m.duration_ms
FROM app.public_shorts AS s
JOIN app.media_assets AS m
    ON m.id = s.media_asset_id
WHERE s.creator_user_id = $1
AND (
    $2::timestamptz IS NULL
    OR s.published_at < $2::timestamptz
    OR (
        s.published_at = $2::timestamptz
        AND s.id < COALESCE($3::uuid, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)
    )
)
ORDER BY s.published_at DESC, s.id DESC
LIMIT $4
`

type ListCreatorProfileShortGridItemsParams struct {
	CreatorUserID     pgtype.UUID
	CursorPublishedAt pgtype.Timestamptz
	CursorShortID     pgtype.UUID
	LimitCount        int32
}

type ListCreatorProfileShortGridItemsRow struct {
	ID              pgtype.UUID
	CreatorUserID   pgtype.UUID
	CanonicalMainID pgtype.UUID
	MediaAssetID    pgtype.UUID
	PublishedAt     pgtype.Timestamptz
	PlaybackUrl     pgtype.Text
	DurationMs      pgtype.Int8
}

func (q *Queries) ListCreatorProfileShortGridItems(ctx context.Context, arg ListCreatorProfileShortGridItemsParams) ([]ListCreatorProfileShortGridItemsRow, error) {
	rows, err := q.db.Query(ctx, listCreatorProfileShortGridItems,
		arg.CreatorUserID,
		arg.CursorPublishedAt,
		arg.CursorShortID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatorProfileShortGridItemsRow
	for rows.Next() {
		var i ListCreatorProfileShortGridItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.PublishedAt,
			&i.PlaybackUrl,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicShortsByCreatorUserID = `-- name: ListPublicShortsByCreatorUserID :many
SELECT id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
FROM app.public_shorts
WHERE creator_user_id = $1
ORDER BY published_at DESC, created_at DESC, id DESC
`

func (q *Queries) ListPublicShortsByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) ([]AppPublicShort, error) {
	rows, err := q.db.Query(ctx, listPublicShortsByCreatorUserID, creatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppPublicShort
	for rows.Next() {
		var i AppPublicShort
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.ApprovedForPublishAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortsByCreatorUserID = `-- name: ListShortsByCreatorUserID :many
SELECT id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
FROM app.shorts
WHERE creator_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListShortsByCreatorUserID(ctx context.Context, creatorUserID pgtype.UUID) ([]AppShort, error) {
	rows, err := q.db.Query(ctx, listShortsByCreatorUserID, creatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppShort
	for rows.Next() {
		var i AppShort
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.ApprovedForPublishAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishShort = `-- name: PublishShort :one
UPDATE app.shorts
SET
    state = 'approved_for_publish',
    approved_for_publish_at = COALESCE(approved_for_publish_at, CURRENT_TIMESTAMP),
    published_at = COALESCE(published_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
`

func (q *Queries) PublishShort(ctx context.Context, id pgtype.UUID) (AppShort, error) {
	row := q.db.QueryRow(ctx, publishShort, id)
	var i AppShort
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.ApprovedForPublishAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShortState = `-- name: UpdateShortState :one
UPDATE app.shorts
SET
    state = $1,
    review_reason_code = $2,
    post_report_state = $3,
    approved_for_publish_at = $4,
    published_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, creator_user_id, canonical_main_id, media_asset_id, state, review_reason_code, post_report_state, approved_for_publish_at, published_at, created_at, updated_at
`

type UpdateShortStateParams struct {
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	ApprovedForPublishAt pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
	ID                   pgtype.UUID
}

func (q *Queries) UpdateShortState(ctx context.Context, arg UpdateShortStateParams) (AppShort, error) {
	row := q.db.QueryRow(ctx, updateShortState,
		arg.State,
		arg.ReviewReasonCode,
		arg.PostReportState,
		arg.ApprovedForPublishAt,
		arg.PublishedAt,
		arg.ID,
	)
	var i AppShort
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CanonicalMainID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.ApprovedForPublishAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
