// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submission_review.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmissionReviewIntake = `-- name: CreateSubmissionReviewIntake :one
INSERT INTO app.submission_review_intakes (
    canonical_main_id,
    creator_user_id,
    status,
    submit_kind,
    previous_intake_id,
    main_media_asset_id,
    main_price_minor,
    ownership_confirmed,
    consent_confirmed,
    submitted_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, canonical_main_id, creator_user_id, status, submit_kind, previous_intake_id, main_media_asset_id, main_price_minor, ownership_confirmed, consent_confirmed, submitted_at, created_at, updated_at
`

type CreateSubmissionReviewIntakeParams struct {
	CanonicalMainID    pgtype.UUID
	CreatorUserID      pgtype.UUID
	Status             string
	SubmitKind         string
	PreviousIntakeID   pgtype.UUID
	MainMediaAssetID   pgtype.UUID
	MainPriceMinor     int64
	OwnershipConfirmed bool
	ConsentConfirmed   bool
	SubmittedAt        pgtype.Timestamptz
}

func (q *Queries) CreateSubmissionReviewIntake(ctx context.Context, arg CreateSubmissionReviewIntakeParams) (AppSubmissionReviewIntake, error) {
	row := q.db.QueryRow(ctx, createSubmissionReviewIntake,
		arg.CanonicalMainID,
		arg.CreatorUserID,
		arg.Status,
		arg.SubmitKind,
		arg.PreviousIntakeID,
		arg.MainMediaAssetID,
		arg.MainPriceMinor,
		arg.OwnershipConfirmed,
		arg.ConsentConfirmed,
		arg.SubmittedAt,
	)
	var i AppSubmissionReviewIntake
	err := row.Scan(
		&i.ID,
		&i.CanonicalMainID,
		&i.CreatorUserID,
		&i.Status,
		&i.SubmitKind,
		&i.PreviousIntakeID,
		&i.MainMediaAssetID,
		&i.MainPriceMinor,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubmissionReviewIntakeShort = `-- name: CreateSubmissionReviewIntakeShort :exec
INSERT INTO app.submission_review_intake_shorts (
    submission_review_intake_id,
    short_id,
    media_asset_id,
    caption
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateSubmissionReviewIntakeShortParams struct {
	SubmissionReviewIntakeID pgtype.UUID
	ShortID                  pgtype.UUID
	MediaAssetID             pgtype.UUID
	Caption                  pgtype.Text
}

func (q *Queries) CreateSubmissionReviewIntakeShort(ctx context.Context, arg CreateSubmissionReviewIntakeShortParams) error {
	_, err := q.db.Exec(ctx, createSubmissionReviewIntakeShort,
		arg.SubmissionReviewIntakeID,
		arg.ShortID,
		arg.MediaAssetID,
		arg.Caption,
	)
	return err
}

const getLatestSubmissionReviewIntakeByCanonicalMainID = `-- name: GetLatestSubmissionReviewIntakeByCanonicalMainID :one
SELECT id, canonical_main_id, creator_user_id, status, submit_kind, previous_intake_id, main_media_asset_id, main_price_minor, ownership_confirmed, consent_confirmed, submitted_at, created_at, updated_at
FROM app.submission_review_intakes
WHERE canonical_main_id = $1
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSubmissionReviewIntakeByCanonicalMainID(ctx context.Context, canonicalMainID pgtype.UUID) (AppSubmissionReviewIntake, error) {
	row := q.db.QueryRow(ctx, getLatestSubmissionReviewIntakeByCanonicalMainID, canonicalMainID)
	var i AppSubmissionReviewIntake
	err := row.Scan(
		&i.ID,
		&i.CanonicalMainID,
		&i.CreatorUserID,
		&i.Status,
		&i.SubmitKind,
		&i.PreviousIntakeID,
		&i.MainMediaAssetID,
		&i.MainPriceMinor,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSubmissionReviewIntakeByCanonicalMainID = `-- name: GetPendingSubmissionReviewIntakeByCanonicalMainID :one
SELECT id, canonical_main_id, creator_user_id, status, submit_kind, previous_intake_id, main_media_asset_id, main_price_minor, ownership_confirmed, consent_confirmed, submitted_at, created_at, updated_at
FROM app.submission_review_intakes
WHERE canonical_main_id = $1
  AND status = 'pending_review'
ORDER BY submitted_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetPendingSubmissionReviewIntakeByCanonicalMainID(ctx context.Context, canonicalMainID pgtype.UUID) (AppSubmissionReviewIntake, error) {
	row := q.db.QueryRow(ctx, getPendingSubmissionReviewIntakeByCanonicalMainID, canonicalMainID)
	var i AppSubmissionReviewIntake
	err := row.Scan(
		&i.ID,
		&i.CanonicalMainID,
		&i.CreatorUserID,
		&i.Status,
		&i.SubmitKind,
		&i.PreviousIntakeID,
		&i.MainMediaAssetID,
		&i.MainPriceMinor,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionReviewMainByIDForUpdate = `-- name: GetSubmissionReviewMainByIDForUpdate :one
SELECT
    m.id,
    m.creator_user_id,
    m.media_asset_id,
    m.state,
    m.review_reason_code,
    m.post_report_state,
    m.price_minor,
    m.currency_code,
    m.ownership_confirmed,
    m.consent_confirmed,
    m.approved_for_unlock_at,
    m.created_at,
    m.updated_at,
    a.processing_state AS media_processing_state
FROM app.mains AS m
JOIN app.media_assets AS a
    ON a.id = m.media_asset_id
WHERE m.id = $1
LIMIT 1
FOR UPDATE OF m
`

type GetSubmissionReviewMainByIDForUpdateRow struct {
	ID                   pgtype.UUID
	CreatorUserID        pgtype.UUID
	MediaAssetID         pgtype.UUID
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	PriceMinor           int64
	CurrencyCode         string
	OwnershipConfirmed   bool
	ConsentConfirmed     bool
	ApprovedForUnlockAt  pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	MediaProcessingState string
}

func (q *Queries) GetSubmissionReviewMainByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetSubmissionReviewMainByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionReviewMainByIDForUpdate, id)
	var i GetSubmissionReviewMainByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.MediaAssetID,
		&i.State,
		&i.ReviewReasonCode,
		&i.PostReportState,
		&i.PriceMinor,
		&i.CurrencyCode,
		&i.OwnershipConfirmed,
		&i.ConsentConfirmed,
		&i.ApprovedForUnlockAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaProcessingState,
	)
	return i, err
}

const listSubmissionReviewShortsByCanonicalMainIDForUpdate = `-- name: ListSubmissionReviewShortsByCanonicalMainIDForUpdate :many
SELECT
    s.id,
    s.creator_user_id,
    s.canonical_main_id,
    s.media_asset_id,
    s.state,
    s.review_reason_code,
    s.post_report_state,
    s.approved_for_publish_at,
    s.published_at,
    s.created_at,
    s.updated_at,
    s.caption,
    a.processing_state AS media_processing_state
FROM app.shorts AS s
JOIN app.media_assets AS a
    ON a.id = s.media_asset_id
WHERE s.canonical_main_id = $1
ORDER BY s.created_at DESC, s.id DESC
FOR UPDATE OF s
`

type ListSubmissionReviewShortsByCanonicalMainIDForUpdateRow struct {
	ID                   pgtype.UUID
	CreatorUserID        pgtype.UUID
	CanonicalMainID      pgtype.UUID
	MediaAssetID         pgtype.UUID
	State                string
	ReviewReasonCode     pgtype.Text
	PostReportState      pgtype.Text
	ApprovedForPublishAt pgtype.Timestamptz
	PublishedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Caption              pgtype.Text
	MediaProcessingState string
}

func (q *Queries) ListSubmissionReviewShortsByCanonicalMainIDForUpdate(ctx context.Context, canonicalMainID pgtype.UUID) ([]ListSubmissionReviewShortsByCanonicalMainIDForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionReviewShortsByCanonicalMainIDForUpdate, canonicalMainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmissionReviewShortsByCanonicalMainIDForUpdateRow
	for rows.Next() {
		var i ListSubmissionReviewShortsByCanonicalMainIDForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorUserID,
			&i.CanonicalMainID,
			&i.MediaAssetID,
			&i.State,
			&i.ReviewReasonCode,
			&i.PostReportState,
			&i.ApprovedForPublishAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Caption,
			&i.MediaProcessingState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
