// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO app.user_profiles (
    user_id,
    display_name,
    handle,
    avatar_url
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING user_id, display_name, handle, avatar_url, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID      pgtype.UUID
	DisplayName string
	Handle      string
	AvatarUrl   pgtype.Text
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (AppUserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
	)
	var i AppUserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByHandle = `-- name: GetUserProfileByHandle :one
SELECT user_id, display_name, handle, avatar_url, created_at, updated_at
FROM app.user_profiles
WHERE handle = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByHandle(ctx context.Context, handle string) (AppUserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByHandle, handle)
	var i AppUserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT user_id, display_name, handle, avatar_url, created_at, updated_at
FROM app.user_profiles
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID pgtype.UUID) (AppUserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i AppUserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE app.user_profiles
SET
    display_name = $1,
    handle = $2,
    avatar_url = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $4
RETURNING user_id, display_name, handle, avatar_url, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string
	Handle      string
	AvatarUrl   pgtype.Text
	UserID      pgtype.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (AppUserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.UserID,
	)
	var i AppUserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
